/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.anz.fastpayment.inward.avro;
@org.apache.avro.specific.AvroGenerated
public enum CompatibilityLevel implements org.apache.avro.generic.GenericEnumSymbol<CompatibilityLevel> {
  BACKWARD, FORWARD, FULL, NONE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"CompatibilityLevel\",\"namespace\":\"com.anz.fastpayment.inward.avro\",\"symbols\":[\"BACKWARD\",\"FORWARD\",\"FULL\",\"NONE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
