/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.anz.fastpayment.inward.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class DbtrAcct extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -323059253891583184L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DbtrAcct\",\"namespace\":\"com.anz.fastpayment.inward.avro\",\"fields\":[{\"name\":\"AcctId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Account identifier\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<DbtrAcct> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DbtrAcct> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<DbtrAcct> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<DbtrAcct> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<DbtrAcct> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this DbtrAcct to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a DbtrAcct from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a DbtrAcct instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static DbtrAcct fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Account identifier */
  private java.lang.String AcctId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DbtrAcct() {}

  /**
   * All-args constructor.
   * @param AcctId Account identifier
   */
  public DbtrAcct(java.lang.String AcctId) {
    this.AcctId = AcctId;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return AcctId;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: AcctId = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'AcctId' field.
   * @return Account identifier
   */
  public java.lang.String getAcctId() {
    return AcctId;
  }


  /**
   * Sets the value of the 'AcctId' field.
   * Account identifier
   * @param value the value to set.
   */
  public void setAcctId(java.lang.String value) {
    this.AcctId = value;
  }

  /**
   * Creates a new DbtrAcct RecordBuilder.
   * @return A new DbtrAcct RecordBuilder
   */
  public static com.anz.fastpayment.inward.avro.DbtrAcct.Builder newBuilder() {
    return new com.anz.fastpayment.inward.avro.DbtrAcct.Builder();
  }

  /**
   * Creates a new DbtrAcct RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DbtrAcct RecordBuilder
   */
  public static com.anz.fastpayment.inward.avro.DbtrAcct.Builder newBuilder(com.anz.fastpayment.inward.avro.DbtrAcct.Builder other) {
    if (other == null) {
      return new com.anz.fastpayment.inward.avro.DbtrAcct.Builder();
    } else {
      return new com.anz.fastpayment.inward.avro.DbtrAcct.Builder(other);
    }
  }

  /**
   * Creates a new DbtrAcct RecordBuilder by copying an existing DbtrAcct instance.
   * @param other The existing instance to copy.
   * @return A new DbtrAcct RecordBuilder
   */
  public static com.anz.fastpayment.inward.avro.DbtrAcct.Builder newBuilder(com.anz.fastpayment.inward.avro.DbtrAcct other) {
    if (other == null) {
      return new com.anz.fastpayment.inward.avro.DbtrAcct.Builder();
    } else {
      return new com.anz.fastpayment.inward.avro.DbtrAcct.Builder(other);
    }
  }

  /**
   * RecordBuilder for DbtrAcct instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DbtrAcct>
    implements org.apache.avro.data.RecordBuilder<DbtrAcct> {

    /** Account identifier */
    private java.lang.String AcctId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.anz.fastpayment.inward.avro.DbtrAcct.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.AcctId)) {
        this.AcctId = data().deepCopy(fields()[0].schema(), other.AcctId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing DbtrAcct instance
     * @param other The existing instance to copy.
     */
    private Builder(com.anz.fastpayment.inward.avro.DbtrAcct other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.AcctId)) {
        this.AcctId = data().deepCopy(fields()[0].schema(), other.AcctId);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'AcctId' field.
      * Account identifier
      * @return The value.
      */
    public java.lang.String getAcctId() {
      return AcctId;
    }


    /**
      * Sets the value of the 'AcctId' field.
      * Account identifier
      * @param value The value of 'AcctId'.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.DbtrAcct.Builder setAcctId(java.lang.String value) {
      validate(fields()[0], value);
      this.AcctId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'AcctId' field has been set.
      * Account identifier
      * @return True if the 'AcctId' field has been set, false otherwise.
      */
    public boolean hasAcctId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'AcctId' field.
      * Account identifier
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.DbtrAcct.Builder clearAcctId() {
      AcctId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DbtrAcct build() {
      try {
        DbtrAcct record = new DbtrAcct();
        record.AcctId = fieldSetFlags()[0] ? this.AcctId : (java.lang.String) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DbtrAcct>
    WRITER$ = (org.apache.avro.io.DatumWriter<DbtrAcct>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DbtrAcct>
    READER$ = (org.apache.avro.io.DatumReader<DbtrAcct>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.AcctId);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.AcctId = in.readString();

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.AcctId = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










