/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.anz.fastpayment.inward.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class EventInfo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6363526870651674305L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EventInfo\",\"namespace\":\"com.anz.fastpayment.inward.avro\",\"fields\":[{\"name\":\"EventCode\",\"type\":\"string\",\"doc\":\"Event code\"},{\"name\":\"EventDescription\",\"type\":\"string\",\"doc\":\"Event description\"},{\"name\":\"EventID\",\"type\":\"string\",\"doc\":\"Event identifier\"},{\"name\":\"EventType\",\"type\":\"string\",\"doc\":\"Event type\"},{\"name\":\"EventProducer\",\"type\":\"string\",\"doc\":\"Event producer\"},{\"name\":\"EventTS\",\"type\":\"string\",\"doc\":\"Event timestamp\"},{\"name\":\"EventTopics\",\"type\":\"string\",\"doc\":\"Event topics\"},{\"name\":\"SystemId\",\"type\":[\"null\",\"string\"],\"doc\":\"System identifier\"},{\"name\":\"Events\",\"type\":{\"type\":\"record\",\"name\":\"Events\",\"fields\":[{\"name\":\"Event\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Event\",\"fields\":[{\"name\":\"EventCode\",\"type\":\"string\",\"doc\":\"Event code\"},{\"name\":\"EventID\",\"type\":\"string\",\"doc\":\"Event identifier\"}]}},\"doc\":\"Array of events\"}]},\"doc\":\"Events information\"},{\"name\":\"EventVersion\",\"type\":[\"null\",\"string\"],\"doc\":\"Event version\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<EventInfo> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<EventInfo> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<EventInfo> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<EventInfo> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<EventInfo> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this EventInfo to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a EventInfo from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a EventInfo instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static EventInfo fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Event code */
  private java.lang.CharSequence EventCode;
  /** Event description */
  private java.lang.CharSequence EventDescription;
  /** Event identifier */
  private java.lang.CharSequence EventID;
  /** Event type */
  private java.lang.CharSequence EventType;
  /** Event producer */
  private java.lang.CharSequence EventProducer;
  /** Event timestamp */
  private java.lang.CharSequence EventTS;
  /** Event topics */
  private java.lang.CharSequence EventTopics;
  /** System identifier */
  private java.lang.CharSequence SystemId;
  /** Events information */
  private com.anz.fastpayment.inward.avro.Events Events;
  /** Event version */
  private java.lang.CharSequence EventVersion;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public EventInfo() {}

  /**
   * All-args constructor.
   * @param EventCode Event code
   * @param EventDescription Event description
   * @param EventID Event identifier
   * @param EventType Event type
   * @param EventProducer Event producer
   * @param EventTS Event timestamp
   * @param EventTopics Event topics
   * @param SystemId System identifier
   * @param Events Events information
   * @param EventVersion Event version
   */
  public EventInfo(java.lang.CharSequence EventCode, java.lang.CharSequence EventDescription, java.lang.CharSequence EventID, java.lang.CharSequence EventType, java.lang.CharSequence EventProducer, java.lang.CharSequence EventTS, java.lang.CharSequence EventTopics, java.lang.CharSequence SystemId, com.anz.fastpayment.inward.avro.Events Events, java.lang.CharSequence EventVersion) {
    this.EventCode = EventCode;
    this.EventDescription = EventDescription;
    this.EventID = EventID;
    this.EventType = EventType;
    this.EventProducer = EventProducer;
    this.EventTS = EventTS;
    this.EventTopics = EventTopics;
    this.SystemId = SystemId;
    this.Events = Events;
    this.EventVersion = EventVersion;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return EventCode;
    case 1: return EventDescription;
    case 2: return EventID;
    case 3: return EventType;
    case 4: return EventProducer;
    case 5: return EventTS;
    case 6: return EventTopics;
    case 7: return SystemId;
    case 8: return Events;
    case 9: return EventVersion;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: EventCode = (java.lang.CharSequence)value$; break;
    case 1: EventDescription = (java.lang.CharSequence)value$; break;
    case 2: EventID = (java.lang.CharSequence)value$; break;
    case 3: EventType = (java.lang.CharSequence)value$; break;
    case 4: EventProducer = (java.lang.CharSequence)value$; break;
    case 5: EventTS = (java.lang.CharSequence)value$; break;
    case 6: EventTopics = (java.lang.CharSequence)value$; break;
    case 7: SystemId = (java.lang.CharSequence)value$; break;
    case 8: Events = (com.anz.fastpayment.inward.avro.Events)value$; break;
    case 9: EventVersion = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'EventCode' field.
   * @return Event code
   */
  public java.lang.CharSequence getEventCode() {
    return EventCode;
  }


  /**
   * Sets the value of the 'EventCode' field.
   * Event code
   * @param value the value to set.
   */
  public void setEventCode(java.lang.CharSequence value) {
    this.EventCode = value;
  }

  /**
   * Gets the value of the 'EventDescription' field.
   * @return Event description
   */
  public java.lang.CharSequence getEventDescription() {
    return EventDescription;
  }


  /**
   * Sets the value of the 'EventDescription' field.
   * Event description
   * @param value the value to set.
   */
  public void setEventDescription(java.lang.CharSequence value) {
    this.EventDescription = value;
  }

  /**
   * Gets the value of the 'EventID' field.
   * @return Event identifier
   */
  public java.lang.CharSequence getEventID() {
    return EventID;
  }


  /**
   * Sets the value of the 'EventID' field.
   * Event identifier
   * @param value the value to set.
   */
  public void setEventID(java.lang.CharSequence value) {
    this.EventID = value;
  }

  /**
   * Gets the value of the 'EventType' field.
   * @return Event type
   */
  public java.lang.CharSequence getEventType() {
    return EventType;
  }


  /**
   * Sets the value of the 'EventType' field.
   * Event type
   * @param value the value to set.
   */
  public void setEventType(java.lang.CharSequence value) {
    this.EventType = value;
  }

  /**
   * Gets the value of the 'EventProducer' field.
   * @return Event producer
   */
  public java.lang.CharSequence getEventProducer() {
    return EventProducer;
  }


  /**
   * Sets the value of the 'EventProducer' field.
   * Event producer
   * @param value the value to set.
   */
  public void setEventProducer(java.lang.CharSequence value) {
    this.EventProducer = value;
  }

  /**
   * Gets the value of the 'EventTS' field.
   * @return Event timestamp
   */
  public java.lang.CharSequence getEventTS() {
    return EventTS;
  }


  /**
   * Sets the value of the 'EventTS' field.
   * Event timestamp
   * @param value the value to set.
   */
  public void setEventTS(java.lang.CharSequence value) {
    this.EventTS = value;
  }

  /**
   * Gets the value of the 'EventTopics' field.
   * @return Event topics
   */
  public java.lang.CharSequence getEventTopics() {
    return EventTopics;
  }


  /**
   * Sets the value of the 'EventTopics' field.
   * Event topics
   * @param value the value to set.
   */
  public void setEventTopics(java.lang.CharSequence value) {
    this.EventTopics = value;
  }

  /**
   * Gets the value of the 'SystemId' field.
   * @return System identifier
   */
  public java.lang.CharSequence getSystemId() {
    return SystemId;
  }


  /**
   * Sets the value of the 'SystemId' field.
   * System identifier
   * @param value the value to set.
   */
  public void setSystemId(java.lang.CharSequence value) {
    this.SystemId = value;
  }

  /**
   * Gets the value of the 'Events' field.
   * @return Events information
   */
  public com.anz.fastpayment.inward.avro.Events getEvents() {
    return Events;
  }


  /**
   * Sets the value of the 'Events' field.
   * Events information
   * @param value the value to set.
   */
  public void setEvents(com.anz.fastpayment.inward.avro.Events value) {
    this.Events = value;
  }

  /**
   * Gets the value of the 'EventVersion' field.
   * @return Event version
   */
  public java.lang.CharSequence getEventVersion() {
    return EventVersion;
  }


  /**
   * Sets the value of the 'EventVersion' field.
   * Event version
   * @param value the value to set.
   */
  public void setEventVersion(java.lang.CharSequence value) {
    this.EventVersion = value;
  }

  /**
   * Creates a new EventInfo RecordBuilder.
   * @return A new EventInfo RecordBuilder
   */
  public static com.anz.fastpayment.inward.avro.EventInfo.Builder newBuilder() {
    return new com.anz.fastpayment.inward.avro.EventInfo.Builder();
  }

  /**
   * Creates a new EventInfo RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new EventInfo RecordBuilder
   */
  public static com.anz.fastpayment.inward.avro.EventInfo.Builder newBuilder(com.anz.fastpayment.inward.avro.EventInfo.Builder other) {
    if (other == null) {
      return new com.anz.fastpayment.inward.avro.EventInfo.Builder();
    } else {
      return new com.anz.fastpayment.inward.avro.EventInfo.Builder(other);
    }
  }

  /**
   * Creates a new EventInfo RecordBuilder by copying an existing EventInfo instance.
   * @param other The existing instance to copy.
   * @return A new EventInfo RecordBuilder
   */
  public static com.anz.fastpayment.inward.avro.EventInfo.Builder newBuilder(com.anz.fastpayment.inward.avro.EventInfo other) {
    if (other == null) {
      return new com.anz.fastpayment.inward.avro.EventInfo.Builder();
    } else {
      return new com.anz.fastpayment.inward.avro.EventInfo.Builder(other);
    }
  }

  /**
   * RecordBuilder for EventInfo instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EventInfo>
    implements org.apache.avro.data.RecordBuilder<EventInfo> {

    /** Event code */
    private java.lang.CharSequence EventCode;
    /** Event description */
    private java.lang.CharSequence EventDescription;
    /** Event identifier */
    private java.lang.CharSequence EventID;
    /** Event type */
    private java.lang.CharSequence EventType;
    /** Event producer */
    private java.lang.CharSequence EventProducer;
    /** Event timestamp */
    private java.lang.CharSequence EventTS;
    /** Event topics */
    private java.lang.CharSequence EventTopics;
    /** System identifier */
    private java.lang.CharSequence SystemId;
    /** Events information */
    private com.anz.fastpayment.inward.avro.Events Events;
    private com.anz.fastpayment.inward.avro.Events.Builder EventsBuilder;
    /** Event version */
    private java.lang.CharSequence EventVersion;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.anz.fastpayment.inward.avro.EventInfo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.EventCode)) {
        this.EventCode = data().deepCopy(fields()[0].schema(), other.EventCode);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.EventDescription)) {
        this.EventDescription = data().deepCopy(fields()[1].schema(), other.EventDescription);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.EventID)) {
        this.EventID = data().deepCopy(fields()[2].schema(), other.EventID);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.EventType)) {
        this.EventType = data().deepCopy(fields()[3].schema(), other.EventType);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.EventProducer)) {
        this.EventProducer = data().deepCopy(fields()[4].schema(), other.EventProducer);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.EventTS)) {
        this.EventTS = data().deepCopy(fields()[5].schema(), other.EventTS);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.EventTopics)) {
        this.EventTopics = data().deepCopy(fields()[6].schema(), other.EventTopics);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.SystemId)) {
        this.SystemId = data().deepCopy(fields()[7].schema(), other.SystemId);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.Events)) {
        this.Events = data().deepCopy(fields()[8].schema(), other.Events);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (other.hasEventsBuilder()) {
        this.EventsBuilder = com.anz.fastpayment.inward.avro.Events.newBuilder(other.getEventsBuilder());
      }
      if (isValidValue(fields()[9], other.EventVersion)) {
        this.EventVersion = data().deepCopy(fields()[9].schema(), other.EventVersion);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
    }

    /**
     * Creates a Builder by copying an existing EventInfo instance
     * @param other The existing instance to copy.
     */
    private Builder(com.anz.fastpayment.inward.avro.EventInfo other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.EventCode)) {
        this.EventCode = data().deepCopy(fields()[0].schema(), other.EventCode);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.EventDescription)) {
        this.EventDescription = data().deepCopy(fields()[1].schema(), other.EventDescription);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.EventID)) {
        this.EventID = data().deepCopy(fields()[2].schema(), other.EventID);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.EventType)) {
        this.EventType = data().deepCopy(fields()[3].schema(), other.EventType);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.EventProducer)) {
        this.EventProducer = data().deepCopy(fields()[4].schema(), other.EventProducer);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.EventTS)) {
        this.EventTS = data().deepCopy(fields()[5].schema(), other.EventTS);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.EventTopics)) {
        this.EventTopics = data().deepCopy(fields()[6].schema(), other.EventTopics);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.SystemId)) {
        this.SystemId = data().deepCopy(fields()[7].schema(), other.SystemId);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.Events)) {
        this.Events = data().deepCopy(fields()[8].schema(), other.Events);
        fieldSetFlags()[8] = true;
      }
      this.EventsBuilder = null;
      if (isValidValue(fields()[9], other.EventVersion)) {
        this.EventVersion = data().deepCopy(fields()[9].schema(), other.EventVersion);
        fieldSetFlags()[9] = true;
      }
    }

    /**
      * Gets the value of the 'EventCode' field.
      * Event code
      * @return The value.
      */
    public java.lang.CharSequence getEventCode() {
      return EventCode;
    }


    /**
      * Sets the value of the 'EventCode' field.
      * Event code
      * @param value The value of 'EventCode'.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.EventInfo.Builder setEventCode(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.EventCode = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'EventCode' field has been set.
      * Event code
      * @return True if the 'EventCode' field has been set, false otherwise.
      */
    public boolean hasEventCode() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'EventCode' field.
      * Event code
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.EventInfo.Builder clearEventCode() {
      EventCode = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'EventDescription' field.
      * Event description
      * @return The value.
      */
    public java.lang.CharSequence getEventDescription() {
      return EventDescription;
    }


    /**
      * Sets the value of the 'EventDescription' field.
      * Event description
      * @param value The value of 'EventDescription'.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.EventInfo.Builder setEventDescription(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.EventDescription = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'EventDescription' field has been set.
      * Event description
      * @return True if the 'EventDescription' field has been set, false otherwise.
      */
    public boolean hasEventDescription() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'EventDescription' field.
      * Event description
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.EventInfo.Builder clearEventDescription() {
      EventDescription = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'EventID' field.
      * Event identifier
      * @return The value.
      */
    public java.lang.CharSequence getEventID() {
      return EventID;
    }


    /**
      * Sets the value of the 'EventID' field.
      * Event identifier
      * @param value The value of 'EventID'.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.EventInfo.Builder setEventID(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.EventID = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'EventID' field has been set.
      * Event identifier
      * @return True if the 'EventID' field has been set, false otherwise.
      */
    public boolean hasEventID() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'EventID' field.
      * Event identifier
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.EventInfo.Builder clearEventID() {
      EventID = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'EventType' field.
      * Event type
      * @return The value.
      */
    public java.lang.CharSequence getEventType() {
      return EventType;
    }


    /**
      * Sets the value of the 'EventType' field.
      * Event type
      * @param value The value of 'EventType'.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.EventInfo.Builder setEventType(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.EventType = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'EventType' field has been set.
      * Event type
      * @return True if the 'EventType' field has been set, false otherwise.
      */
    public boolean hasEventType() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'EventType' field.
      * Event type
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.EventInfo.Builder clearEventType() {
      EventType = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'EventProducer' field.
      * Event producer
      * @return The value.
      */
    public java.lang.CharSequence getEventProducer() {
      return EventProducer;
    }


    /**
      * Sets the value of the 'EventProducer' field.
      * Event producer
      * @param value The value of 'EventProducer'.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.EventInfo.Builder setEventProducer(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.EventProducer = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'EventProducer' field has been set.
      * Event producer
      * @return True if the 'EventProducer' field has been set, false otherwise.
      */
    public boolean hasEventProducer() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'EventProducer' field.
      * Event producer
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.EventInfo.Builder clearEventProducer() {
      EventProducer = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'EventTS' field.
      * Event timestamp
      * @return The value.
      */
    public java.lang.CharSequence getEventTS() {
      return EventTS;
    }


    /**
      * Sets the value of the 'EventTS' field.
      * Event timestamp
      * @param value The value of 'EventTS'.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.EventInfo.Builder setEventTS(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.EventTS = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'EventTS' field has been set.
      * Event timestamp
      * @return True if the 'EventTS' field has been set, false otherwise.
      */
    public boolean hasEventTS() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'EventTS' field.
      * Event timestamp
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.EventInfo.Builder clearEventTS() {
      EventTS = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'EventTopics' field.
      * Event topics
      * @return The value.
      */
    public java.lang.CharSequence getEventTopics() {
      return EventTopics;
    }


    /**
      * Sets the value of the 'EventTopics' field.
      * Event topics
      * @param value The value of 'EventTopics'.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.EventInfo.Builder setEventTopics(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.EventTopics = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'EventTopics' field has been set.
      * Event topics
      * @return True if the 'EventTopics' field has been set, false otherwise.
      */
    public boolean hasEventTopics() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'EventTopics' field.
      * Event topics
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.EventInfo.Builder clearEventTopics() {
      EventTopics = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'SystemId' field.
      * System identifier
      * @return The value.
      */
    public java.lang.CharSequence getSystemId() {
      return SystemId;
    }


    /**
      * Sets the value of the 'SystemId' field.
      * System identifier
      * @param value The value of 'SystemId'.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.EventInfo.Builder setSystemId(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.SystemId = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'SystemId' field has been set.
      * System identifier
      * @return True if the 'SystemId' field has been set, false otherwise.
      */
    public boolean hasSystemId() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'SystemId' field.
      * System identifier
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.EventInfo.Builder clearSystemId() {
      SystemId = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'Events' field.
      * Events information
      * @return The value.
      */
    public com.anz.fastpayment.inward.avro.Events getEvents() {
      return Events;
    }


    /**
      * Sets the value of the 'Events' field.
      * Events information
      * @param value The value of 'Events'.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.EventInfo.Builder setEvents(com.anz.fastpayment.inward.avro.Events value) {
      validate(fields()[8], value);
      this.EventsBuilder = null;
      this.Events = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'Events' field has been set.
      * Events information
      * @return True if the 'Events' field has been set, false otherwise.
      */
    public boolean hasEvents() {
      return fieldSetFlags()[8];
    }

    /**
     * Gets the Builder instance for the 'Events' field and creates one if it doesn't exist yet.
     * Events information
     * @return This builder.
     */
    public com.anz.fastpayment.inward.avro.Events.Builder getEventsBuilder() {
      if (EventsBuilder == null) {
        if (hasEvents()) {
          setEventsBuilder(com.anz.fastpayment.inward.avro.Events.newBuilder(Events));
        } else {
          setEventsBuilder(com.anz.fastpayment.inward.avro.Events.newBuilder());
        }
      }
      return EventsBuilder;
    }

    /**
     * Sets the Builder instance for the 'Events' field
     * Events information
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.anz.fastpayment.inward.avro.EventInfo.Builder setEventsBuilder(com.anz.fastpayment.inward.avro.Events.Builder value) {
      clearEvents();
      EventsBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'Events' field has an active Builder instance
     * Events information
     * @return True if the 'Events' field has an active Builder instance
     */
    public boolean hasEventsBuilder() {
      return EventsBuilder != null;
    }

    /**
      * Clears the value of the 'Events' field.
      * Events information
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.EventInfo.Builder clearEvents() {
      Events = null;
      EventsBuilder = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'EventVersion' field.
      * Event version
      * @return The value.
      */
    public java.lang.CharSequence getEventVersion() {
      return EventVersion;
    }


    /**
      * Sets the value of the 'EventVersion' field.
      * Event version
      * @param value The value of 'EventVersion'.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.EventInfo.Builder setEventVersion(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.EventVersion = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'EventVersion' field has been set.
      * Event version
      * @return True if the 'EventVersion' field has been set, false otherwise.
      */
    public boolean hasEventVersion() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'EventVersion' field.
      * Event version
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.EventInfo.Builder clearEventVersion() {
      EventVersion = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public EventInfo build() {
      try {
        EventInfo record = new EventInfo();
        record.EventCode = fieldSetFlags()[0] ? this.EventCode : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.EventDescription = fieldSetFlags()[1] ? this.EventDescription : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.EventID = fieldSetFlags()[2] ? this.EventID : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.EventType = fieldSetFlags()[3] ? this.EventType : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.EventProducer = fieldSetFlags()[4] ? this.EventProducer : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.EventTS = fieldSetFlags()[5] ? this.EventTS : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.EventTopics = fieldSetFlags()[6] ? this.EventTopics : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.SystemId = fieldSetFlags()[7] ? this.SystemId : (java.lang.CharSequence) defaultValue(fields()[7]);
        if (EventsBuilder != null) {
          try {
            record.Events = this.EventsBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("Events"));
            throw e;
          }
        } else {
          record.Events = fieldSetFlags()[8] ? this.Events : (com.anz.fastpayment.inward.avro.Events) defaultValue(fields()[8]);
        }
        record.EventVersion = fieldSetFlags()[9] ? this.EventVersion : (java.lang.CharSequence) defaultValue(fields()[9]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<EventInfo>
    WRITER$ = (org.apache.avro.io.DatumWriter<EventInfo>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<EventInfo>
    READER$ = (org.apache.avro.io.DatumReader<EventInfo>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.EventCode);

    out.writeString(this.EventDescription);

    out.writeString(this.EventID);

    out.writeString(this.EventType);

    out.writeString(this.EventProducer);

    out.writeString(this.EventTS);

    out.writeString(this.EventTopics);

    if (this.SystemId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.SystemId);
    }

    this.Events.customEncode(out);

    if (this.EventVersion == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.EventVersion);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.EventCode = in.readString(this.EventCode instanceof Utf8 ? (Utf8)this.EventCode : null);

      this.EventDescription = in.readString(this.EventDescription instanceof Utf8 ? (Utf8)this.EventDescription : null);

      this.EventID = in.readString(this.EventID instanceof Utf8 ? (Utf8)this.EventID : null);

      this.EventType = in.readString(this.EventType instanceof Utf8 ? (Utf8)this.EventType : null);

      this.EventProducer = in.readString(this.EventProducer instanceof Utf8 ? (Utf8)this.EventProducer : null);

      this.EventTS = in.readString(this.EventTS instanceof Utf8 ? (Utf8)this.EventTS : null);

      this.EventTopics = in.readString(this.EventTopics instanceof Utf8 ? (Utf8)this.EventTopics : null);

      if (in.readIndex() != 1) {
        in.readNull();
        this.SystemId = null;
      } else {
        this.SystemId = in.readString(this.SystemId instanceof Utf8 ? (Utf8)this.SystemId : null);
      }

      if (this.Events == null) {
        this.Events = new com.anz.fastpayment.inward.avro.Events();
      }
      this.Events.customDecode(in);

      if (in.readIndex() != 1) {
        in.readNull();
        this.EventVersion = null;
      } else {
        this.EventVersion = in.readString(this.EventVersion instanceof Utf8 ? (Utf8)this.EventVersion : null);
      }

    } else {
      for (int i = 0; i < 10; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.EventCode = in.readString(this.EventCode instanceof Utf8 ? (Utf8)this.EventCode : null);
          break;

        case 1:
          this.EventDescription = in.readString(this.EventDescription instanceof Utf8 ? (Utf8)this.EventDescription : null);
          break;

        case 2:
          this.EventID = in.readString(this.EventID instanceof Utf8 ? (Utf8)this.EventID : null);
          break;

        case 3:
          this.EventType = in.readString(this.EventType instanceof Utf8 ? (Utf8)this.EventType : null);
          break;

        case 4:
          this.EventProducer = in.readString(this.EventProducer instanceof Utf8 ? (Utf8)this.EventProducer : null);
          break;

        case 5:
          this.EventTS = in.readString(this.EventTS instanceof Utf8 ? (Utf8)this.EventTS : null);
          break;

        case 6:
          this.EventTopics = in.readString(this.EventTopics instanceof Utf8 ? (Utf8)this.EventTopics : null);
          break;

        case 7:
          if (in.readIndex() != 1) {
            in.readNull();
            this.SystemId = null;
          } else {
            this.SystemId = in.readString(this.SystemId instanceof Utf8 ? (Utf8)this.SystemId : null);
          }
          break;

        case 8:
          if (this.Events == null) {
            this.Events = new com.anz.fastpayment.inward.avro.Events();
          }
          this.Events.customDecode(in);
          break;

        case 9:
          if (in.readIndex() != 1) {
            in.readNull();
            this.EventVersion = null;
          } else {
            this.EventVersion = in.readString(this.EventVersion instanceof Utf8 ? (Utf8)this.EventVersion : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










