/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.anz.fastpayment.inward.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Events extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -9046612637459260465L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Events\",\"namespace\":\"com.anz.fastpayment.inward.avro\",\"fields\":[{\"name\":\"Event\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Event\",\"fields\":[{\"name\":\"EventCode\",\"type\":\"string\",\"doc\":\"Event code\"},{\"name\":\"EventID\",\"type\":\"string\",\"doc\":\"Event identifier\"}]}},\"doc\":\"Array of events\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Events> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Events> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Events> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Events> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Events> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Events to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Events from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Events instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Events fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Array of events */
  private java.util.List<com.anz.fastpayment.inward.avro.Event> Event;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Events() {}

  /**
   * All-args constructor.
   * @param Event Array of events
   */
  public Events(java.util.List<com.anz.fastpayment.inward.avro.Event> Event) {
    this.Event = Event;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return Event;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: Event = (java.util.List<com.anz.fastpayment.inward.avro.Event>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'Event' field.
   * @return Array of events
   */
  public java.util.List<com.anz.fastpayment.inward.avro.Event> getEvent() {
    return Event;
  }


  /**
   * Sets the value of the 'Event' field.
   * Array of events
   * @param value the value to set.
   */
  public void setEvent(java.util.List<com.anz.fastpayment.inward.avro.Event> value) {
    this.Event = value;
  }

  /**
   * Creates a new Events RecordBuilder.
   * @return A new Events RecordBuilder
   */
  public static com.anz.fastpayment.inward.avro.Events.Builder newBuilder() {
    return new com.anz.fastpayment.inward.avro.Events.Builder();
  }

  /**
   * Creates a new Events RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Events RecordBuilder
   */
  public static com.anz.fastpayment.inward.avro.Events.Builder newBuilder(com.anz.fastpayment.inward.avro.Events.Builder other) {
    if (other == null) {
      return new com.anz.fastpayment.inward.avro.Events.Builder();
    } else {
      return new com.anz.fastpayment.inward.avro.Events.Builder(other);
    }
  }

  /**
   * Creates a new Events RecordBuilder by copying an existing Events instance.
   * @param other The existing instance to copy.
   * @return A new Events RecordBuilder
   */
  public static com.anz.fastpayment.inward.avro.Events.Builder newBuilder(com.anz.fastpayment.inward.avro.Events other) {
    if (other == null) {
      return new com.anz.fastpayment.inward.avro.Events.Builder();
    } else {
      return new com.anz.fastpayment.inward.avro.Events.Builder(other);
    }
  }

  /**
   * RecordBuilder for Events instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Events>
    implements org.apache.avro.data.RecordBuilder<Events> {

    /** Array of events */
    private java.util.List<com.anz.fastpayment.inward.avro.Event> Event;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.anz.fastpayment.inward.avro.Events.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.Event)) {
        this.Event = data().deepCopy(fields()[0].schema(), other.Event);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing Events instance
     * @param other The existing instance to copy.
     */
    private Builder(com.anz.fastpayment.inward.avro.Events other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.Event)) {
        this.Event = data().deepCopy(fields()[0].schema(), other.Event);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'Event' field.
      * Array of events
      * @return The value.
      */
    public java.util.List<com.anz.fastpayment.inward.avro.Event> getEvent() {
      return Event;
    }


    /**
      * Sets the value of the 'Event' field.
      * Array of events
      * @param value The value of 'Event'.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.Events.Builder setEvent(java.util.List<com.anz.fastpayment.inward.avro.Event> value) {
      validate(fields()[0], value);
      this.Event = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'Event' field has been set.
      * Array of events
      * @return True if the 'Event' field has been set, false otherwise.
      */
    public boolean hasEvent() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'Event' field.
      * Array of events
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.Events.Builder clearEvent() {
      Event = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Events build() {
      try {
        Events record = new Events();
        record.Event = fieldSetFlags()[0] ? this.Event : (java.util.List<com.anz.fastpayment.inward.avro.Event>) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Events>
    WRITER$ = (org.apache.avro.io.DatumWriter<Events>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Events>
    READER$ = (org.apache.avro.io.DatumReader<Events>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    long size0 = this.Event.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (com.anz.fastpayment.inward.avro.Event e0: this.Event) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      long size0 = in.readArrayStart();
      java.util.List<com.anz.fastpayment.inward.avro.Event> a0 = this.Event;
      if (a0 == null) {
        a0 = new SpecificData.Array<com.anz.fastpayment.inward.avro.Event>((int)size0, SCHEMA$.getField("Event").schema());
        this.Event = a0;
      } else a0.clear();
      SpecificData.Array<com.anz.fastpayment.inward.avro.Event> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.anz.fastpayment.inward.avro.Event>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          com.anz.fastpayment.inward.avro.Event e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new com.anz.fastpayment.inward.avro.Event();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          long size0 = in.readArrayStart();
          java.util.List<com.anz.fastpayment.inward.avro.Event> a0 = this.Event;
          if (a0 == null) {
            a0 = new SpecificData.Array<com.anz.fastpayment.inward.avro.Event>((int)size0, SCHEMA$.getField("Event").schema());
            this.Event = a0;
          } else a0.clear();
          SpecificData.Array<com.anz.fastpayment.inward.avro.Event> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.anz.fastpayment.inward.avro.Event>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              com.anz.fastpayment.inward.avro.Event e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new com.anz.fastpayment.inward.avro.Event();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










