/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.anz.fastpayment.inward.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class MsgCtxt extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3367752317948508994L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MsgCtxt\",\"namespace\":\"com.anz.fastpayment.inward.avro\",\"fields\":[{\"name\":\"OrigMsgTyp\",\"type\":\"string\",\"doc\":\"Original message type\"},{\"name\":\"InstdClrgPref\",\"type\":\"string\",\"doc\":\"Instructed clearing preference\"},{\"name\":\"InstdMoPCat\",\"type\":\"string\",\"doc\":\"Instructed method of payment category\"},{\"name\":\"Site\",\"type\":\"string\",\"doc\":\"Site\"},{\"name\":\"BaseAmt\",\"type\":\"double\",\"doc\":\"Base amount\"},{\"name\":\"BaseCcy\",\"type\":\"string\",\"doc\":\"Base currency\"},{\"name\":\"SenderBIC\",\"type\":\"string\",\"doc\":\"Sender BIC\"},{\"name\":\"ProcCtryCd\",\"type\":\"string\",\"doc\":\"Processing country code\"},{\"name\":\"Department\",\"type\":\"string\",\"doc\":\"Department\"},{\"name\":\"MsgId\",\"type\":\"string\",\"doc\":\"Message identifier\"},{\"name\":\"Direction\",\"type\":\"string\",\"doc\":\"Direction\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<MsgCtxt> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<MsgCtxt> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<MsgCtxt> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<MsgCtxt> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<MsgCtxt> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this MsgCtxt to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a MsgCtxt from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a MsgCtxt instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static MsgCtxt fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Original message type */
  private java.lang.CharSequence OrigMsgTyp;
  /** Instructed clearing preference */
  private java.lang.CharSequence InstdClrgPref;
  /** Instructed method of payment category */
  private java.lang.CharSequence InstdMoPCat;
  /** Site */
  private java.lang.CharSequence Site;
  /** Base amount */
  private double BaseAmt;
  /** Base currency */
  private java.lang.CharSequence BaseCcy;
  /** Sender BIC */
  private java.lang.CharSequence SenderBIC;
  /** Processing country code */
  private java.lang.CharSequence ProcCtryCd;
  /** Department */
  private java.lang.CharSequence Department;
  /** Message identifier */
  private java.lang.CharSequence MsgId;
  /** Direction */
  private java.lang.CharSequence Direction;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public MsgCtxt() {}

  /**
   * All-args constructor.
   * @param OrigMsgTyp Original message type
   * @param InstdClrgPref Instructed clearing preference
   * @param InstdMoPCat Instructed method of payment category
   * @param Site Site
   * @param BaseAmt Base amount
   * @param BaseCcy Base currency
   * @param SenderBIC Sender BIC
   * @param ProcCtryCd Processing country code
   * @param Department Department
   * @param MsgId Message identifier
   * @param Direction Direction
   */
  public MsgCtxt(java.lang.CharSequence OrigMsgTyp, java.lang.CharSequence InstdClrgPref, java.lang.CharSequence InstdMoPCat, java.lang.CharSequence Site, java.lang.Double BaseAmt, java.lang.CharSequence BaseCcy, java.lang.CharSequence SenderBIC, java.lang.CharSequence ProcCtryCd, java.lang.CharSequence Department, java.lang.CharSequence MsgId, java.lang.CharSequence Direction) {
    this.OrigMsgTyp = OrigMsgTyp;
    this.InstdClrgPref = InstdClrgPref;
    this.InstdMoPCat = InstdMoPCat;
    this.Site = Site;
    this.BaseAmt = BaseAmt;
    this.BaseCcy = BaseCcy;
    this.SenderBIC = SenderBIC;
    this.ProcCtryCd = ProcCtryCd;
    this.Department = Department;
    this.MsgId = MsgId;
    this.Direction = Direction;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return OrigMsgTyp;
    case 1: return InstdClrgPref;
    case 2: return InstdMoPCat;
    case 3: return Site;
    case 4: return BaseAmt;
    case 5: return BaseCcy;
    case 6: return SenderBIC;
    case 7: return ProcCtryCd;
    case 8: return Department;
    case 9: return MsgId;
    case 10: return Direction;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: OrigMsgTyp = (java.lang.CharSequence)value$; break;
    case 1: InstdClrgPref = (java.lang.CharSequence)value$; break;
    case 2: InstdMoPCat = (java.lang.CharSequence)value$; break;
    case 3: Site = (java.lang.CharSequence)value$; break;
    case 4: BaseAmt = (java.lang.Double)value$; break;
    case 5: BaseCcy = (java.lang.CharSequence)value$; break;
    case 6: SenderBIC = (java.lang.CharSequence)value$; break;
    case 7: ProcCtryCd = (java.lang.CharSequence)value$; break;
    case 8: Department = (java.lang.CharSequence)value$; break;
    case 9: MsgId = (java.lang.CharSequence)value$; break;
    case 10: Direction = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'OrigMsgTyp' field.
   * @return Original message type
   */
  public java.lang.CharSequence getOrigMsgTyp() {
    return OrigMsgTyp;
  }


  /**
   * Sets the value of the 'OrigMsgTyp' field.
   * Original message type
   * @param value the value to set.
   */
  public void setOrigMsgTyp(java.lang.CharSequence value) {
    this.OrigMsgTyp = value;
  }

  /**
   * Gets the value of the 'InstdClrgPref' field.
   * @return Instructed clearing preference
   */
  public java.lang.CharSequence getInstdClrgPref() {
    return InstdClrgPref;
  }


  /**
   * Sets the value of the 'InstdClrgPref' field.
   * Instructed clearing preference
   * @param value the value to set.
   */
  public void setInstdClrgPref(java.lang.CharSequence value) {
    this.InstdClrgPref = value;
  }

  /**
   * Gets the value of the 'InstdMoPCat' field.
   * @return Instructed method of payment category
   */
  public java.lang.CharSequence getInstdMoPCat() {
    return InstdMoPCat;
  }


  /**
   * Sets the value of the 'InstdMoPCat' field.
   * Instructed method of payment category
   * @param value the value to set.
   */
  public void setInstdMoPCat(java.lang.CharSequence value) {
    this.InstdMoPCat = value;
  }

  /**
   * Gets the value of the 'Site' field.
   * @return Site
   */
  public java.lang.CharSequence getSite() {
    return Site;
  }


  /**
   * Sets the value of the 'Site' field.
   * Site
   * @param value the value to set.
   */
  public void setSite(java.lang.CharSequence value) {
    this.Site = value;
  }

  /**
   * Gets the value of the 'BaseAmt' field.
   * @return Base amount
   */
  public double getBaseAmt() {
    return BaseAmt;
  }


  /**
   * Sets the value of the 'BaseAmt' field.
   * Base amount
   * @param value the value to set.
   */
  public void setBaseAmt(double value) {
    this.BaseAmt = value;
  }

  /**
   * Gets the value of the 'BaseCcy' field.
   * @return Base currency
   */
  public java.lang.CharSequence getBaseCcy() {
    return BaseCcy;
  }


  /**
   * Sets the value of the 'BaseCcy' field.
   * Base currency
   * @param value the value to set.
   */
  public void setBaseCcy(java.lang.CharSequence value) {
    this.BaseCcy = value;
  }

  /**
   * Gets the value of the 'SenderBIC' field.
   * @return Sender BIC
   */
  public java.lang.CharSequence getSenderBIC() {
    return SenderBIC;
  }


  /**
   * Sets the value of the 'SenderBIC' field.
   * Sender BIC
   * @param value the value to set.
   */
  public void setSenderBIC(java.lang.CharSequence value) {
    this.SenderBIC = value;
  }

  /**
   * Gets the value of the 'ProcCtryCd' field.
   * @return Processing country code
   */
  public java.lang.CharSequence getProcCtryCd() {
    return ProcCtryCd;
  }


  /**
   * Sets the value of the 'ProcCtryCd' field.
   * Processing country code
   * @param value the value to set.
   */
  public void setProcCtryCd(java.lang.CharSequence value) {
    this.ProcCtryCd = value;
  }

  /**
   * Gets the value of the 'Department' field.
   * @return Department
   */
  public java.lang.CharSequence getDepartment() {
    return Department;
  }


  /**
   * Sets the value of the 'Department' field.
   * Department
   * @param value the value to set.
   */
  public void setDepartment(java.lang.CharSequence value) {
    this.Department = value;
  }

  /**
   * Gets the value of the 'MsgId' field.
   * @return Message identifier
   */
  public java.lang.CharSequence getMsgId() {
    return MsgId;
  }


  /**
   * Sets the value of the 'MsgId' field.
   * Message identifier
   * @param value the value to set.
   */
  public void setMsgId(java.lang.CharSequence value) {
    this.MsgId = value;
  }

  /**
   * Gets the value of the 'Direction' field.
   * @return Direction
   */
  public java.lang.CharSequence getDirection() {
    return Direction;
  }


  /**
   * Sets the value of the 'Direction' field.
   * Direction
   * @param value the value to set.
   */
  public void setDirection(java.lang.CharSequence value) {
    this.Direction = value;
  }

  /**
   * Creates a new MsgCtxt RecordBuilder.
   * @return A new MsgCtxt RecordBuilder
   */
  public static com.anz.fastpayment.inward.avro.MsgCtxt.Builder newBuilder() {
    return new com.anz.fastpayment.inward.avro.MsgCtxt.Builder();
  }

  /**
   * Creates a new MsgCtxt RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new MsgCtxt RecordBuilder
   */
  public static com.anz.fastpayment.inward.avro.MsgCtxt.Builder newBuilder(com.anz.fastpayment.inward.avro.MsgCtxt.Builder other) {
    if (other == null) {
      return new com.anz.fastpayment.inward.avro.MsgCtxt.Builder();
    } else {
      return new com.anz.fastpayment.inward.avro.MsgCtxt.Builder(other);
    }
  }

  /**
   * Creates a new MsgCtxt RecordBuilder by copying an existing MsgCtxt instance.
   * @param other The existing instance to copy.
   * @return A new MsgCtxt RecordBuilder
   */
  public static com.anz.fastpayment.inward.avro.MsgCtxt.Builder newBuilder(com.anz.fastpayment.inward.avro.MsgCtxt other) {
    if (other == null) {
      return new com.anz.fastpayment.inward.avro.MsgCtxt.Builder();
    } else {
      return new com.anz.fastpayment.inward.avro.MsgCtxt.Builder(other);
    }
  }

  /**
   * RecordBuilder for MsgCtxt instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MsgCtxt>
    implements org.apache.avro.data.RecordBuilder<MsgCtxt> {

    /** Original message type */
    private java.lang.CharSequence OrigMsgTyp;
    /** Instructed clearing preference */
    private java.lang.CharSequence InstdClrgPref;
    /** Instructed method of payment category */
    private java.lang.CharSequence InstdMoPCat;
    /** Site */
    private java.lang.CharSequence Site;
    /** Base amount */
    private double BaseAmt;
    /** Base currency */
    private java.lang.CharSequence BaseCcy;
    /** Sender BIC */
    private java.lang.CharSequence SenderBIC;
    /** Processing country code */
    private java.lang.CharSequence ProcCtryCd;
    /** Department */
    private java.lang.CharSequence Department;
    /** Message identifier */
    private java.lang.CharSequence MsgId;
    /** Direction */
    private java.lang.CharSequence Direction;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.anz.fastpayment.inward.avro.MsgCtxt.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.OrigMsgTyp)) {
        this.OrigMsgTyp = data().deepCopy(fields()[0].schema(), other.OrigMsgTyp);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.InstdClrgPref)) {
        this.InstdClrgPref = data().deepCopy(fields()[1].schema(), other.InstdClrgPref);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.InstdMoPCat)) {
        this.InstdMoPCat = data().deepCopy(fields()[2].schema(), other.InstdMoPCat);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.Site)) {
        this.Site = data().deepCopy(fields()[3].schema(), other.Site);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.BaseAmt)) {
        this.BaseAmt = data().deepCopy(fields()[4].schema(), other.BaseAmt);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.BaseCcy)) {
        this.BaseCcy = data().deepCopy(fields()[5].schema(), other.BaseCcy);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.SenderBIC)) {
        this.SenderBIC = data().deepCopy(fields()[6].schema(), other.SenderBIC);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.ProcCtryCd)) {
        this.ProcCtryCd = data().deepCopy(fields()[7].schema(), other.ProcCtryCd);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.Department)) {
        this.Department = data().deepCopy(fields()[8].schema(), other.Department);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.MsgId)) {
        this.MsgId = data().deepCopy(fields()[9].schema(), other.MsgId);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.Direction)) {
        this.Direction = data().deepCopy(fields()[10].schema(), other.Direction);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
    }

    /**
     * Creates a Builder by copying an existing MsgCtxt instance
     * @param other The existing instance to copy.
     */
    private Builder(com.anz.fastpayment.inward.avro.MsgCtxt other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.OrigMsgTyp)) {
        this.OrigMsgTyp = data().deepCopy(fields()[0].schema(), other.OrigMsgTyp);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.InstdClrgPref)) {
        this.InstdClrgPref = data().deepCopy(fields()[1].schema(), other.InstdClrgPref);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.InstdMoPCat)) {
        this.InstdMoPCat = data().deepCopy(fields()[2].schema(), other.InstdMoPCat);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.Site)) {
        this.Site = data().deepCopy(fields()[3].schema(), other.Site);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.BaseAmt)) {
        this.BaseAmt = data().deepCopy(fields()[4].schema(), other.BaseAmt);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.BaseCcy)) {
        this.BaseCcy = data().deepCopy(fields()[5].schema(), other.BaseCcy);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.SenderBIC)) {
        this.SenderBIC = data().deepCopy(fields()[6].schema(), other.SenderBIC);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.ProcCtryCd)) {
        this.ProcCtryCd = data().deepCopy(fields()[7].schema(), other.ProcCtryCd);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.Department)) {
        this.Department = data().deepCopy(fields()[8].schema(), other.Department);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.MsgId)) {
        this.MsgId = data().deepCopy(fields()[9].schema(), other.MsgId);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.Direction)) {
        this.Direction = data().deepCopy(fields()[10].schema(), other.Direction);
        fieldSetFlags()[10] = true;
      }
    }

    /**
      * Gets the value of the 'OrigMsgTyp' field.
      * Original message type
      * @return The value.
      */
    public java.lang.CharSequence getOrigMsgTyp() {
      return OrigMsgTyp;
    }


    /**
      * Sets the value of the 'OrigMsgTyp' field.
      * Original message type
      * @param value The value of 'OrigMsgTyp'.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.MsgCtxt.Builder setOrigMsgTyp(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.OrigMsgTyp = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'OrigMsgTyp' field has been set.
      * Original message type
      * @return True if the 'OrigMsgTyp' field has been set, false otherwise.
      */
    public boolean hasOrigMsgTyp() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'OrigMsgTyp' field.
      * Original message type
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.MsgCtxt.Builder clearOrigMsgTyp() {
      OrigMsgTyp = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'InstdClrgPref' field.
      * Instructed clearing preference
      * @return The value.
      */
    public java.lang.CharSequence getInstdClrgPref() {
      return InstdClrgPref;
    }


    /**
      * Sets the value of the 'InstdClrgPref' field.
      * Instructed clearing preference
      * @param value The value of 'InstdClrgPref'.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.MsgCtxt.Builder setInstdClrgPref(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.InstdClrgPref = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'InstdClrgPref' field has been set.
      * Instructed clearing preference
      * @return True if the 'InstdClrgPref' field has been set, false otherwise.
      */
    public boolean hasInstdClrgPref() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'InstdClrgPref' field.
      * Instructed clearing preference
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.MsgCtxt.Builder clearInstdClrgPref() {
      InstdClrgPref = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'InstdMoPCat' field.
      * Instructed method of payment category
      * @return The value.
      */
    public java.lang.CharSequence getInstdMoPCat() {
      return InstdMoPCat;
    }


    /**
      * Sets the value of the 'InstdMoPCat' field.
      * Instructed method of payment category
      * @param value The value of 'InstdMoPCat'.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.MsgCtxt.Builder setInstdMoPCat(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.InstdMoPCat = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'InstdMoPCat' field has been set.
      * Instructed method of payment category
      * @return True if the 'InstdMoPCat' field has been set, false otherwise.
      */
    public boolean hasInstdMoPCat() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'InstdMoPCat' field.
      * Instructed method of payment category
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.MsgCtxt.Builder clearInstdMoPCat() {
      InstdMoPCat = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'Site' field.
      * Site
      * @return The value.
      */
    public java.lang.CharSequence getSite() {
      return Site;
    }


    /**
      * Sets the value of the 'Site' field.
      * Site
      * @param value The value of 'Site'.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.MsgCtxt.Builder setSite(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.Site = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'Site' field has been set.
      * Site
      * @return True if the 'Site' field has been set, false otherwise.
      */
    public boolean hasSite() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'Site' field.
      * Site
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.MsgCtxt.Builder clearSite() {
      Site = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'BaseAmt' field.
      * Base amount
      * @return The value.
      */
    public double getBaseAmt() {
      return BaseAmt;
    }


    /**
      * Sets the value of the 'BaseAmt' field.
      * Base amount
      * @param value The value of 'BaseAmt'.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.MsgCtxt.Builder setBaseAmt(double value) {
      validate(fields()[4], value);
      this.BaseAmt = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'BaseAmt' field has been set.
      * Base amount
      * @return True if the 'BaseAmt' field has been set, false otherwise.
      */
    public boolean hasBaseAmt() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'BaseAmt' field.
      * Base amount
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.MsgCtxt.Builder clearBaseAmt() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'BaseCcy' field.
      * Base currency
      * @return The value.
      */
    public java.lang.CharSequence getBaseCcy() {
      return BaseCcy;
    }


    /**
      * Sets the value of the 'BaseCcy' field.
      * Base currency
      * @param value The value of 'BaseCcy'.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.MsgCtxt.Builder setBaseCcy(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.BaseCcy = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'BaseCcy' field has been set.
      * Base currency
      * @return True if the 'BaseCcy' field has been set, false otherwise.
      */
    public boolean hasBaseCcy() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'BaseCcy' field.
      * Base currency
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.MsgCtxt.Builder clearBaseCcy() {
      BaseCcy = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'SenderBIC' field.
      * Sender BIC
      * @return The value.
      */
    public java.lang.CharSequence getSenderBIC() {
      return SenderBIC;
    }


    /**
      * Sets the value of the 'SenderBIC' field.
      * Sender BIC
      * @param value The value of 'SenderBIC'.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.MsgCtxt.Builder setSenderBIC(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.SenderBIC = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'SenderBIC' field has been set.
      * Sender BIC
      * @return True if the 'SenderBIC' field has been set, false otherwise.
      */
    public boolean hasSenderBIC() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'SenderBIC' field.
      * Sender BIC
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.MsgCtxt.Builder clearSenderBIC() {
      SenderBIC = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'ProcCtryCd' field.
      * Processing country code
      * @return The value.
      */
    public java.lang.CharSequence getProcCtryCd() {
      return ProcCtryCd;
    }


    /**
      * Sets the value of the 'ProcCtryCd' field.
      * Processing country code
      * @param value The value of 'ProcCtryCd'.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.MsgCtxt.Builder setProcCtryCd(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.ProcCtryCd = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'ProcCtryCd' field has been set.
      * Processing country code
      * @return True if the 'ProcCtryCd' field has been set, false otherwise.
      */
    public boolean hasProcCtryCd() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'ProcCtryCd' field.
      * Processing country code
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.MsgCtxt.Builder clearProcCtryCd() {
      ProcCtryCd = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'Department' field.
      * Department
      * @return The value.
      */
    public java.lang.CharSequence getDepartment() {
      return Department;
    }


    /**
      * Sets the value of the 'Department' field.
      * Department
      * @param value The value of 'Department'.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.MsgCtxt.Builder setDepartment(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.Department = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'Department' field has been set.
      * Department
      * @return True if the 'Department' field has been set, false otherwise.
      */
    public boolean hasDepartment() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'Department' field.
      * Department
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.MsgCtxt.Builder clearDepartment() {
      Department = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'MsgId' field.
      * Message identifier
      * @return The value.
      */
    public java.lang.CharSequence getMsgId() {
      return MsgId;
    }


    /**
      * Sets the value of the 'MsgId' field.
      * Message identifier
      * @param value The value of 'MsgId'.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.MsgCtxt.Builder setMsgId(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.MsgId = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'MsgId' field has been set.
      * Message identifier
      * @return True if the 'MsgId' field has been set, false otherwise.
      */
    public boolean hasMsgId() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'MsgId' field.
      * Message identifier
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.MsgCtxt.Builder clearMsgId() {
      MsgId = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'Direction' field.
      * Direction
      * @return The value.
      */
    public java.lang.CharSequence getDirection() {
      return Direction;
    }


    /**
      * Sets the value of the 'Direction' field.
      * Direction
      * @param value The value of 'Direction'.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.MsgCtxt.Builder setDirection(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.Direction = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'Direction' field has been set.
      * Direction
      * @return True if the 'Direction' field has been set, false otherwise.
      */
    public boolean hasDirection() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'Direction' field.
      * Direction
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.MsgCtxt.Builder clearDirection() {
      Direction = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public MsgCtxt build() {
      try {
        MsgCtxt record = new MsgCtxt();
        record.OrigMsgTyp = fieldSetFlags()[0] ? this.OrigMsgTyp : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.InstdClrgPref = fieldSetFlags()[1] ? this.InstdClrgPref : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.InstdMoPCat = fieldSetFlags()[2] ? this.InstdMoPCat : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.Site = fieldSetFlags()[3] ? this.Site : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.BaseAmt = fieldSetFlags()[4] ? this.BaseAmt : (java.lang.Double) defaultValue(fields()[4]);
        record.BaseCcy = fieldSetFlags()[5] ? this.BaseCcy : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.SenderBIC = fieldSetFlags()[6] ? this.SenderBIC : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.ProcCtryCd = fieldSetFlags()[7] ? this.ProcCtryCd : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.Department = fieldSetFlags()[8] ? this.Department : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.MsgId = fieldSetFlags()[9] ? this.MsgId : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.Direction = fieldSetFlags()[10] ? this.Direction : (java.lang.CharSequence) defaultValue(fields()[10]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<MsgCtxt>
    WRITER$ = (org.apache.avro.io.DatumWriter<MsgCtxt>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<MsgCtxt>
    READER$ = (org.apache.avro.io.DatumReader<MsgCtxt>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.OrigMsgTyp);

    out.writeString(this.InstdClrgPref);

    out.writeString(this.InstdMoPCat);

    out.writeString(this.Site);

    out.writeDouble(this.BaseAmt);

    out.writeString(this.BaseCcy);

    out.writeString(this.SenderBIC);

    out.writeString(this.ProcCtryCd);

    out.writeString(this.Department);

    out.writeString(this.MsgId);

    out.writeString(this.Direction);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.OrigMsgTyp = in.readString(this.OrigMsgTyp instanceof Utf8 ? (Utf8)this.OrigMsgTyp : null);

      this.InstdClrgPref = in.readString(this.InstdClrgPref instanceof Utf8 ? (Utf8)this.InstdClrgPref : null);

      this.InstdMoPCat = in.readString(this.InstdMoPCat instanceof Utf8 ? (Utf8)this.InstdMoPCat : null);

      this.Site = in.readString(this.Site instanceof Utf8 ? (Utf8)this.Site : null);

      this.BaseAmt = in.readDouble();

      this.BaseCcy = in.readString(this.BaseCcy instanceof Utf8 ? (Utf8)this.BaseCcy : null);

      this.SenderBIC = in.readString(this.SenderBIC instanceof Utf8 ? (Utf8)this.SenderBIC : null);

      this.ProcCtryCd = in.readString(this.ProcCtryCd instanceof Utf8 ? (Utf8)this.ProcCtryCd : null);

      this.Department = in.readString(this.Department instanceof Utf8 ? (Utf8)this.Department : null);

      this.MsgId = in.readString(this.MsgId instanceof Utf8 ? (Utf8)this.MsgId : null);

      this.Direction = in.readString(this.Direction instanceof Utf8 ? (Utf8)this.Direction : null);

    } else {
      for (int i = 0; i < 11; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.OrigMsgTyp = in.readString(this.OrigMsgTyp instanceof Utf8 ? (Utf8)this.OrigMsgTyp : null);
          break;

        case 1:
          this.InstdClrgPref = in.readString(this.InstdClrgPref instanceof Utf8 ? (Utf8)this.InstdClrgPref : null);
          break;

        case 2:
          this.InstdMoPCat = in.readString(this.InstdMoPCat instanceof Utf8 ? (Utf8)this.InstdMoPCat : null);
          break;

        case 3:
          this.Site = in.readString(this.Site instanceof Utf8 ? (Utf8)this.Site : null);
          break;

        case 4:
          this.BaseAmt = in.readDouble();
          break;

        case 5:
          this.BaseCcy = in.readString(this.BaseCcy instanceof Utf8 ? (Utf8)this.BaseCcy : null);
          break;

        case 6:
          this.SenderBIC = in.readString(this.SenderBIC instanceof Utf8 ? (Utf8)this.SenderBIC : null);
          break;

        case 7:
          this.ProcCtryCd = in.readString(this.ProcCtryCd instanceof Utf8 ? (Utf8)this.ProcCtryCd : null);
          break;

        case 8:
          this.Department = in.readString(this.Department instanceof Utf8 ? (Utf8)this.Department : null);
          break;

        case 9:
          this.MsgId = in.readString(this.MsgId instanceof Utf8 ? (Utf8)this.MsgId : null);
          break;

        case 10:
          this.Direction = in.readString(this.Direction instanceof Utf8 ? (Utf8)this.Direction : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










