/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.anz.fastpayment.inward.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class MsgHdr extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7242426940069271363L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MsgHdr\",\"namespace\":\"com.anz.fastpayment.inward.avro\",\"fields\":[{\"name\":\"ClientDt\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Client date\"},{\"name\":\"ClientName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Client name\"},{\"name\":\"PartyId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Party identifier\"},{\"name\":\"Version\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Version\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<MsgHdr> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<MsgHdr> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<MsgHdr> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<MsgHdr> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<MsgHdr> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this MsgHdr to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a MsgHdr from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a MsgHdr instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static MsgHdr fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Client date */
  private java.lang.String ClientDt;
  /** Client name */
  private java.lang.String ClientName;
  /** Party identifier */
  private java.lang.String PartyId;
  /** Version */
  private java.lang.String Version;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public MsgHdr() {}

  /**
   * All-args constructor.
   * @param ClientDt Client date
   * @param ClientName Client name
   * @param PartyId Party identifier
   * @param Version Version
   */
  public MsgHdr(java.lang.String ClientDt, java.lang.String ClientName, java.lang.String PartyId, java.lang.String Version) {
    this.ClientDt = ClientDt;
    this.ClientName = ClientName;
    this.PartyId = PartyId;
    this.Version = Version;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return ClientDt;
    case 1: return ClientName;
    case 2: return PartyId;
    case 3: return Version;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: ClientDt = value$ != null ? value$.toString() : null; break;
    case 1: ClientName = value$ != null ? value$.toString() : null; break;
    case 2: PartyId = value$ != null ? value$.toString() : null; break;
    case 3: Version = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'ClientDt' field.
   * @return Client date
   */
  public java.lang.String getClientDt() {
    return ClientDt;
  }


  /**
   * Sets the value of the 'ClientDt' field.
   * Client date
   * @param value the value to set.
   */
  public void setClientDt(java.lang.String value) {
    this.ClientDt = value;
  }

  /**
   * Gets the value of the 'ClientName' field.
   * @return Client name
   */
  public java.lang.String getClientName() {
    return ClientName;
  }


  /**
   * Sets the value of the 'ClientName' field.
   * Client name
   * @param value the value to set.
   */
  public void setClientName(java.lang.String value) {
    this.ClientName = value;
  }

  /**
   * Gets the value of the 'PartyId' field.
   * @return Party identifier
   */
  public java.lang.String getPartyId() {
    return PartyId;
  }


  /**
   * Sets the value of the 'PartyId' field.
   * Party identifier
   * @param value the value to set.
   */
  public void setPartyId(java.lang.String value) {
    this.PartyId = value;
  }

  /**
   * Gets the value of the 'Version' field.
   * @return Version
   */
  public java.lang.String getVersion() {
    return Version;
  }


  /**
   * Sets the value of the 'Version' field.
   * Version
   * @param value the value to set.
   */
  public void setVersion(java.lang.String value) {
    this.Version = value;
  }

  /**
   * Creates a new MsgHdr RecordBuilder.
   * @return A new MsgHdr RecordBuilder
   */
  public static com.anz.fastpayment.inward.avro.MsgHdr.Builder newBuilder() {
    return new com.anz.fastpayment.inward.avro.MsgHdr.Builder();
  }

  /**
   * Creates a new MsgHdr RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new MsgHdr RecordBuilder
   */
  public static com.anz.fastpayment.inward.avro.MsgHdr.Builder newBuilder(com.anz.fastpayment.inward.avro.MsgHdr.Builder other) {
    if (other == null) {
      return new com.anz.fastpayment.inward.avro.MsgHdr.Builder();
    } else {
      return new com.anz.fastpayment.inward.avro.MsgHdr.Builder(other);
    }
  }

  /**
   * Creates a new MsgHdr RecordBuilder by copying an existing MsgHdr instance.
   * @param other The existing instance to copy.
   * @return A new MsgHdr RecordBuilder
   */
  public static com.anz.fastpayment.inward.avro.MsgHdr.Builder newBuilder(com.anz.fastpayment.inward.avro.MsgHdr other) {
    if (other == null) {
      return new com.anz.fastpayment.inward.avro.MsgHdr.Builder();
    } else {
      return new com.anz.fastpayment.inward.avro.MsgHdr.Builder(other);
    }
  }

  /**
   * RecordBuilder for MsgHdr instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MsgHdr>
    implements org.apache.avro.data.RecordBuilder<MsgHdr> {

    /** Client date */
    private java.lang.String ClientDt;
    /** Client name */
    private java.lang.String ClientName;
    /** Party identifier */
    private java.lang.String PartyId;
    /** Version */
    private java.lang.String Version;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.anz.fastpayment.inward.avro.MsgHdr.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.ClientDt)) {
        this.ClientDt = data().deepCopy(fields()[0].schema(), other.ClientDt);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.ClientName)) {
        this.ClientName = data().deepCopy(fields()[1].schema(), other.ClientName);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.PartyId)) {
        this.PartyId = data().deepCopy(fields()[2].schema(), other.PartyId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.Version)) {
        this.Version = data().deepCopy(fields()[3].schema(), other.Version);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing MsgHdr instance
     * @param other The existing instance to copy.
     */
    private Builder(com.anz.fastpayment.inward.avro.MsgHdr other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.ClientDt)) {
        this.ClientDt = data().deepCopy(fields()[0].schema(), other.ClientDt);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.ClientName)) {
        this.ClientName = data().deepCopy(fields()[1].schema(), other.ClientName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.PartyId)) {
        this.PartyId = data().deepCopy(fields()[2].schema(), other.PartyId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.Version)) {
        this.Version = data().deepCopy(fields()[3].schema(), other.Version);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'ClientDt' field.
      * Client date
      * @return The value.
      */
    public java.lang.String getClientDt() {
      return ClientDt;
    }


    /**
      * Sets the value of the 'ClientDt' field.
      * Client date
      * @param value The value of 'ClientDt'.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.MsgHdr.Builder setClientDt(java.lang.String value) {
      validate(fields()[0], value);
      this.ClientDt = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'ClientDt' field has been set.
      * Client date
      * @return True if the 'ClientDt' field has been set, false otherwise.
      */
    public boolean hasClientDt() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'ClientDt' field.
      * Client date
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.MsgHdr.Builder clearClientDt() {
      ClientDt = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'ClientName' field.
      * Client name
      * @return The value.
      */
    public java.lang.String getClientName() {
      return ClientName;
    }


    /**
      * Sets the value of the 'ClientName' field.
      * Client name
      * @param value The value of 'ClientName'.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.MsgHdr.Builder setClientName(java.lang.String value) {
      validate(fields()[1], value);
      this.ClientName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'ClientName' field has been set.
      * Client name
      * @return True if the 'ClientName' field has been set, false otherwise.
      */
    public boolean hasClientName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'ClientName' field.
      * Client name
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.MsgHdr.Builder clearClientName() {
      ClientName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'PartyId' field.
      * Party identifier
      * @return The value.
      */
    public java.lang.String getPartyId() {
      return PartyId;
    }


    /**
      * Sets the value of the 'PartyId' field.
      * Party identifier
      * @param value The value of 'PartyId'.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.MsgHdr.Builder setPartyId(java.lang.String value) {
      validate(fields()[2], value);
      this.PartyId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'PartyId' field has been set.
      * Party identifier
      * @return True if the 'PartyId' field has been set, false otherwise.
      */
    public boolean hasPartyId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'PartyId' field.
      * Party identifier
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.MsgHdr.Builder clearPartyId() {
      PartyId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'Version' field.
      * Version
      * @return The value.
      */
    public java.lang.String getVersion() {
      return Version;
    }


    /**
      * Sets the value of the 'Version' field.
      * Version
      * @param value The value of 'Version'.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.MsgHdr.Builder setVersion(java.lang.String value) {
      validate(fields()[3], value);
      this.Version = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'Version' field has been set.
      * Version
      * @return True if the 'Version' field has been set, false otherwise.
      */
    public boolean hasVersion() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'Version' field.
      * Version
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.MsgHdr.Builder clearVersion() {
      Version = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public MsgHdr build() {
      try {
        MsgHdr record = new MsgHdr();
        record.ClientDt = fieldSetFlags()[0] ? this.ClientDt : (java.lang.String) defaultValue(fields()[0]);
        record.ClientName = fieldSetFlags()[1] ? this.ClientName : (java.lang.String) defaultValue(fields()[1]);
        record.PartyId = fieldSetFlags()[2] ? this.PartyId : (java.lang.String) defaultValue(fields()[2]);
        record.Version = fieldSetFlags()[3] ? this.Version : (java.lang.String) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<MsgHdr>
    WRITER$ = (org.apache.avro.io.DatumWriter<MsgHdr>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<MsgHdr>
    READER$ = (org.apache.avro.io.DatumReader<MsgHdr>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.ClientDt);

    out.writeString(this.ClientName);

    out.writeString(this.PartyId);

    out.writeString(this.Version);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.ClientDt = in.readString();

      this.ClientName = in.readString();

      this.PartyId = in.readString();

      this.Version = in.readString();

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.ClientDt = in.readString();
          break;

        case 1:
          this.ClientName = in.readString();
          break;

        case 2:
          this.PartyId = in.readString();
          break;

        case 3:
          this.Version = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










