/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.anz.fastpayment.inward.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Response message with original data plus processing trailer */
@org.apache.avro.specific.AvroGenerated
public class ProcessedTransactionResponse extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 9186566198209478037L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ProcessedTransactionResponse\",\"namespace\":\"com.anz.fastpayment.inward.avro\",\"doc\":\"Response message with original data plus processing trailer\",\"fields\":[{\"name\":\"Header\",\"type\":{\"type\":\"record\",\"name\":\"ResponseHeader\",\"fields\":[{\"name\":\"MessageId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Unique message identifier\"},{\"name\":\"CreationDateTime\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Message creation timestamp\"},{\"name\":\"ProcessingDateTime\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"When processing completed\"}]},\"doc\":\"Response header information\"},{\"name\":\"Body\",\"type\":{\"type\":\"record\",\"name\":\"ResponseBody\",\"fields\":[{\"name\":\"OriginalMessage\",\"type\":\"bytes\",\"doc\":\"Original input message preserved as bytes\"},{\"name\":\"TransactionId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Transaction identifier\"},{\"name\":\"ProcessingStatus\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Overall processing status\"}]},\"doc\":\"Response body with original message and processing info\"},{\"name\":\"Trailer\",\"type\":{\"type\":\"record\",\"name\":\"ServiceStatus\",\"fields\":[{\"name\":\"status\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Processing status: SUCCESS, FAILED, PARTIAL\"},{\"name\":\"StatusCode\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"HTTP-style status code: 200, 400, 500\"},{\"name\":\"StatusDesc\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},\"doc\":\"Array of status descriptions or validation errors\"}]},\"doc\":\"Service status trailer with validation results\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ProcessedTransactionResponse> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ProcessedTransactionResponse> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ProcessedTransactionResponse> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ProcessedTransactionResponse> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ProcessedTransactionResponse> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ProcessedTransactionResponse to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ProcessedTransactionResponse from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ProcessedTransactionResponse instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ProcessedTransactionResponse fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Response header information */
  private com.anz.fastpayment.inward.avro.ResponseHeader Header;
  /** Response body with original message and processing info */
  private com.anz.fastpayment.inward.avro.ResponseBody Body;
  /** Service status trailer with validation results */
  private com.anz.fastpayment.inward.avro.ServiceStatus Trailer;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ProcessedTransactionResponse() {}

  /**
   * All-args constructor.
   * @param Header Response header information
   * @param Body Response body with original message and processing info
   * @param Trailer Service status trailer with validation results
   */
  public ProcessedTransactionResponse(com.anz.fastpayment.inward.avro.ResponseHeader Header, com.anz.fastpayment.inward.avro.ResponseBody Body, com.anz.fastpayment.inward.avro.ServiceStatus Trailer) {
    this.Header = Header;
    this.Body = Body;
    this.Trailer = Trailer;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return Header;
    case 1: return Body;
    case 2: return Trailer;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: Header = (com.anz.fastpayment.inward.avro.ResponseHeader)value$; break;
    case 1: Body = (com.anz.fastpayment.inward.avro.ResponseBody)value$; break;
    case 2: Trailer = (com.anz.fastpayment.inward.avro.ServiceStatus)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'Header' field.
   * @return Response header information
   */
  public com.anz.fastpayment.inward.avro.ResponseHeader getHeader() {
    return Header;
  }


  /**
   * Sets the value of the 'Header' field.
   * Response header information
   * @param value the value to set.
   */
  public void setHeader(com.anz.fastpayment.inward.avro.ResponseHeader value) {
    this.Header = value;
  }

  /**
   * Gets the value of the 'Body' field.
   * @return Response body with original message and processing info
   */
  public com.anz.fastpayment.inward.avro.ResponseBody getBody() {
    return Body;
  }


  /**
   * Sets the value of the 'Body' field.
   * Response body with original message and processing info
   * @param value the value to set.
   */
  public void setBody(com.anz.fastpayment.inward.avro.ResponseBody value) {
    this.Body = value;
  }

  /**
   * Gets the value of the 'Trailer' field.
   * @return Service status trailer with validation results
   */
  public com.anz.fastpayment.inward.avro.ServiceStatus getTrailer() {
    return Trailer;
  }


  /**
   * Sets the value of the 'Trailer' field.
   * Service status trailer with validation results
   * @param value the value to set.
   */
  public void setTrailer(com.anz.fastpayment.inward.avro.ServiceStatus value) {
    this.Trailer = value;
  }

  /**
   * Creates a new ProcessedTransactionResponse RecordBuilder.
   * @return A new ProcessedTransactionResponse RecordBuilder
   */
  public static com.anz.fastpayment.inward.avro.ProcessedTransactionResponse.Builder newBuilder() {
    return new com.anz.fastpayment.inward.avro.ProcessedTransactionResponse.Builder();
  }

  /**
   * Creates a new ProcessedTransactionResponse RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ProcessedTransactionResponse RecordBuilder
   */
  public static com.anz.fastpayment.inward.avro.ProcessedTransactionResponse.Builder newBuilder(com.anz.fastpayment.inward.avro.ProcessedTransactionResponse.Builder other) {
    if (other == null) {
      return new com.anz.fastpayment.inward.avro.ProcessedTransactionResponse.Builder();
    } else {
      return new com.anz.fastpayment.inward.avro.ProcessedTransactionResponse.Builder(other);
    }
  }

  /**
   * Creates a new ProcessedTransactionResponse RecordBuilder by copying an existing ProcessedTransactionResponse instance.
   * @param other The existing instance to copy.
   * @return A new ProcessedTransactionResponse RecordBuilder
   */
  public static com.anz.fastpayment.inward.avro.ProcessedTransactionResponse.Builder newBuilder(com.anz.fastpayment.inward.avro.ProcessedTransactionResponse other) {
    if (other == null) {
      return new com.anz.fastpayment.inward.avro.ProcessedTransactionResponse.Builder();
    } else {
      return new com.anz.fastpayment.inward.avro.ProcessedTransactionResponse.Builder(other);
    }
  }

  /**
   * RecordBuilder for ProcessedTransactionResponse instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ProcessedTransactionResponse>
    implements org.apache.avro.data.RecordBuilder<ProcessedTransactionResponse> {

    /** Response header information */
    private com.anz.fastpayment.inward.avro.ResponseHeader Header;
    private com.anz.fastpayment.inward.avro.ResponseHeader.Builder HeaderBuilder;
    /** Response body with original message and processing info */
    private com.anz.fastpayment.inward.avro.ResponseBody Body;
    private com.anz.fastpayment.inward.avro.ResponseBody.Builder BodyBuilder;
    /** Service status trailer with validation results */
    private com.anz.fastpayment.inward.avro.ServiceStatus Trailer;
    private com.anz.fastpayment.inward.avro.ServiceStatus.Builder TrailerBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.anz.fastpayment.inward.avro.ProcessedTransactionResponse.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.Header)) {
        this.Header = data().deepCopy(fields()[0].schema(), other.Header);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (other.hasHeaderBuilder()) {
        this.HeaderBuilder = com.anz.fastpayment.inward.avro.ResponseHeader.newBuilder(other.getHeaderBuilder());
      }
      if (isValidValue(fields()[1], other.Body)) {
        this.Body = data().deepCopy(fields()[1].schema(), other.Body);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (other.hasBodyBuilder()) {
        this.BodyBuilder = com.anz.fastpayment.inward.avro.ResponseBody.newBuilder(other.getBodyBuilder());
      }
      if (isValidValue(fields()[2], other.Trailer)) {
        this.Trailer = data().deepCopy(fields()[2].schema(), other.Trailer);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (other.hasTrailerBuilder()) {
        this.TrailerBuilder = com.anz.fastpayment.inward.avro.ServiceStatus.newBuilder(other.getTrailerBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing ProcessedTransactionResponse instance
     * @param other The existing instance to copy.
     */
    private Builder(com.anz.fastpayment.inward.avro.ProcessedTransactionResponse other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.Header)) {
        this.Header = data().deepCopy(fields()[0].schema(), other.Header);
        fieldSetFlags()[0] = true;
      }
      this.HeaderBuilder = null;
      if (isValidValue(fields()[1], other.Body)) {
        this.Body = data().deepCopy(fields()[1].schema(), other.Body);
        fieldSetFlags()[1] = true;
      }
      this.BodyBuilder = null;
      if (isValidValue(fields()[2], other.Trailer)) {
        this.Trailer = data().deepCopy(fields()[2].schema(), other.Trailer);
        fieldSetFlags()[2] = true;
      }
      this.TrailerBuilder = null;
    }

    /**
      * Gets the value of the 'Header' field.
      * Response header information
      * @return The value.
      */
    public com.anz.fastpayment.inward.avro.ResponseHeader getHeader() {
      return Header;
    }


    /**
      * Sets the value of the 'Header' field.
      * Response header information
      * @param value The value of 'Header'.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.ProcessedTransactionResponse.Builder setHeader(com.anz.fastpayment.inward.avro.ResponseHeader value) {
      validate(fields()[0], value);
      this.HeaderBuilder = null;
      this.Header = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'Header' field has been set.
      * Response header information
      * @return True if the 'Header' field has been set, false otherwise.
      */
    public boolean hasHeader() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'Header' field and creates one if it doesn't exist yet.
     * Response header information
     * @return This builder.
     */
    public com.anz.fastpayment.inward.avro.ResponseHeader.Builder getHeaderBuilder() {
      if (HeaderBuilder == null) {
        if (hasHeader()) {
          setHeaderBuilder(com.anz.fastpayment.inward.avro.ResponseHeader.newBuilder(Header));
        } else {
          setHeaderBuilder(com.anz.fastpayment.inward.avro.ResponseHeader.newBuilder());
        }
      }
      return HeaderBuilder;
    }

    /**
     * Sets the Builder instance for the 'Header' field
     * Response header information
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.anz.fastpayment.inward.avro.ProcessedTransactionResponse.Builder setHeaderBuilder(com.anz.fastpayment.inward.avro.ResponseHeader.Builder value) {
      clearHeader();
      HeaderBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'Header' field has an active Builder instance
     * Response header information
     * @return True if the 'Header' field has an active Builder instance
     */
    public boolean hasHeaderBuilder() {
      return HeaderBuilder != null;
    }

    /**
      * Clears the value of the 'Header' field.
      * Response header information
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.ProcessedTransactionResponse.Builder clearHeader() {
      Header = null;
      HeaderBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'Body' field.
      * Response body with original message and processing info
      * @return The value.
      */
    public com.anz.fastpayment.inward.avro.ResponseBody getBody() {
      return Body;
    }


    /**
      * Sets the value of the 'Body' field.
      * Response body with original message and processing info
      * @param value The value of 'Body'.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.ProcessedTransactionResponse.Builder setBody(com.anz.fastpayment.inward.avro.ResponseBody value) {
      validate(fields()[1], value);
      this.BodyBuilder = null;
      this.Body = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'Body' field has been set.
      * Response body with original message and processing info
      * @return True if the 'Body' field has been set, false otherwise.
      */
    public boolean hasBody() {
      return fieldSetFlags()[1];
    }

    /**
     * Gets the Builder instance for the 'Body' field and creates one if it doesn't exist yet.
     * Response body with original message and processing info
     * @return This builder.
     */
    public com.anz.fastpayment.inward.avro.ResponseBody.Builder getBodyBuilder() {
      if (BodyBuilder == null) {
        if (hasBody()) {
          setBodyBuilder(com.anz.fastpayment.inward.avro.ResponseBody.newBuilder(Body));
        } else {
          setBodyBuilder(com.anz.fastpayment.inward.avro.ResponseBody.newBuilder());
        }
      }
      return BodyBuilder;
    }

    /**
     * Sets the Builder instance for the 'Body' field
     * Response body with original message and processing info
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.anz.fastpayment.inward.avro.ProcessedTransactionResponse.Builder setBodyBuilder(com.anz.fastpayment.inward.avro.ResponseBody.Builder value) {
      clearBody();
      BodyBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'Body' field has an active Builder instance
     * Response body with original message and processing info
     * @return True if the 'Body' field has an active Builder instance
     */
    public boolean hasBodyBuilder() {
      return BodyBuilder != null;
    }

    /**
      * Clears the value of the 'Body' field.
      * Response body with original message and processing info
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.ProcessedTransactionResponse.Builder clearBody() {
      Body = null;
      BodyBuilder = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'Trailer' field.
      * Service status trailer with validation results
      * @return The value.
      */
    public com.anz.fastpayment.inward.avro.ServiceStatus getTrailer() {
      return Trailer;
    }


    /**
      * Sets the value of the 'Trailer' field.
      * Service status trailer with validation results
      * @param value The value of 'Trailer'.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.ProcessedTransactionResponse.Builder setTrailer(com.anz.fastpayment.inward.avro.ServiceStatus value) {
      validate(fields()[2], value);
      this.TrailerBuilder = null;
      this.Trailer = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'Trailer' field has been set.
      * Service status trailer with validation results
      * @return True if the 'Trailer' field has been set, false otherwise.
      */
    public boolean hasTrailer() {
      return fieldSetFlags()[2];
    }

    /**
     * Gets the Builder instance for the 'Trailer' field and creates one if it doesn't exist yet.
     * Service status trailer with validation results
     * @return This builder.
     */
    public com.anz.fastpayment.inward.avro.ServiceStatus.Builder getTrailerBuilder() {
      if (TrailerBuilder == null) {
        if (hasTrailer()) {
          setTrailerBuilder(com.anz.fastpayment.inward.avro.ServiceStatus.newBuilder(Trailer));
        } else {
          setTrailerBuilder(com.anz.fastpayment.inward.avro.ServiceStatus.newBuilder());
        }
      }
      return TrailerBuilder;
    }

    /**
     * Sets the Builder instance for the 'Trailer' field
     * Service status trailer with validation results
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.anz.fastpayment.inward.avro.ProcessedTransactionResponse.Builder setTrailerBuilder(com.anz.fastpayment.inward.avro.ServiceStatus.Builder value) {
      clearTrailer();
      TrailerBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'Trailer' field has an active Builder instance
     * Service status trailer with validation results
     * @return True if the 'Trailer' field has an active Builder instance
     */
    public boolean hasTrailerBuilder() {
      return TrailerBuilder != null;
    }

    /**
      * Clears the value of the 'Trailer' field.
      * Service status trailer with validation results
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.ProcessedTransactionResponse.Builder clearTrailer() {
      Trailer = null;
      TrailerBuilder = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ProcessedTransactionResponse build() {
      try {
        ProcessedTransactionResponse record = new ProcessedTransactionResponse();
        if (HeaderBuilder != null) {
          try {
            record.Header = this.HeaderBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("Header"));
            throw e;
          }
        } else {
          record.Header = fieldSetFlags()[0] ? this.Header : (com.anz.fastpayment.inward.avro.ResponseHeader) defaultValue(fields()[0]);
        }
        if (BodyBuilder != null) {
          try {
            record.Body = this.BodyBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("Body"));
            throw e;
          }
        } else {
          record.Body = fieldSetFlags()[1] ? this.Body : (com.anz.fastpayment.inward.avro.ResponseBody) defaultValue(fields()[1]);
        }
        if (TrailerBuilder != null) {
          try {
            record.Trailer = this.TrailerBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("Trailer"));
            throw e;
          }
        } else {
          record.Trailer = fieldSetFlags()[2] ? this.Trailer : (com.anz.fastpayment.inward.avro.ServiceStatus) defaultValue(fields()[2]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ProcessedTransactionResponse>
    WRITER$ = (org.apache.avro.io.DatumWriter<ProcessedTransactionResponse>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ProcessedTransactionResponse>
    READER$ = (org.apache.avro.io.DatumReader<ProcessedTransactionResponse>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    this.Header.customEncode(out);

    this.Body.customEncode(out);

    this.Trailer.customEncode(out);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (this.Header == null) {
        this.Header = new com.anz.fastpayment.inward.avro.ResponseHeader();
      }
      this.Header.customDecode(in);

      if (this.Body == null) {
        this.Body = new com.anz.fastpayment.inward.avro.ResponseBody();
      }
      this.Body.customDecode(in);

      if (this.Trailer == null) {
        this.Trailer = new com.anz.fastpayment.inward.avro.ServiceStatus();
      }
      this.Trailer.customDecode(in);

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (this.Header == null) {
            this.Header = new com.anz.fastpayment.inward.avro.ResponseHeader();
          }
          this.Header.customDecode(in);
          break;

        case 1:
          if (this.Body == null) {
            this.Body = new com.anz.fastpayment.inward.avro.ResponseBody();
          }
          this.Body.customDecode(in);
          break;

        case 2:
          if (this.Trailer == null) {
            this.Trailer = new com.anz.fastpayment.inward.avro.ServiceStatus();
          }
          this.Trailer.customDecode(in);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










