/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.anz.fastpayment.inward.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ResponseHeader extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1190030938930891442L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ResponseHeader\",\"namespace\":\"com.anz.fastpayment.inward.avro\",\"fields\":[{\"name\":\"MessageId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Unique message identifier\"},{\"name\":\"CreationDateTime\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Message creation timestamp\"},{\"name\":\"ProcessingDateTime\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"When processing completed\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ResponseHeader> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ResponseHeader> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ResponseHeader> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ResponseHeader> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ResponseHeader> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ResponseHeader to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ResponseHeader from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ResponseHeader instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ResponseHeader fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Unique message identifier */
  private java.lang.String MessageId;
  /** Message creation timestamp */
  private java.lang.String CreationDateTime;
  /** When processing completed */
  private java.lang.String ProcessingDateTime;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ResponseHeader() {}

  /**
   * All-args constructor.
   * @param MessageId Unique message identifier
   * @param CreationDateTime Message creation timestamp
   * @param ProcessingDateTime When processing completed
   */
  public ResponseHeader(java.lang.String MessageId, java.lang.String CreationDateTime, java.lang.String ProcessingDateTime) {
    this.MessageId = MessageId;
    this.CreationDateTime = CreationDateTime;
    this.ProcessingDateTime = ProcessingDateTime;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return MessageId;
    case 1: return CreationDateTime;
    case 2: return ProcessingDateTime;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: MessageId = value$ != null ? value$.toString() : null; break;
    case 1: CreationDateTime = value$ != null ? value$.toString() : null; break;
    case 2: ProcessingDateTime = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'MessageId' field.
   * @return Unique message identifier
   */
  public java.lang.String getMessageId() {
    return MessageId;
  }


  /**
   * Sets the value of the 'MessageId' field.
   * Unique message identifier
   * @param value the value to set.
   */
  public void setMessageId(java.lang.String value) {
    this.MessageId = value;
  }

  /**
   * Gets the value of the 'CreationDateTime' field.
   * @return Message creation timestamp
   */
  public java.lang.String getCreationDateTime() {
    return CreationDateTime;
  }


  /**
   * Sets the value of the 'CreationDateTime' field.
   * Message creation timestamp
   * @param value the value to set.
   */
  public void setCreationDateTime(java.lang.String value) {
    this.CreationDateTime = value;
  }

  /**
   * Gets the value of the 'ProcessingDateTime' field.
   * @return When processing completed
   */
  public java.lang.String getProcessingDateTime() {
    return ProcessingDateTime;
  }


  /**
   * Sets the value of the 'ProcessingDateTime' field.
   * When processing completed
   * @param value the value to set.
   */
  public void setProcessingDateTime(java.lang.String value) {
    this.ProcessingDateTime = value;
  }

  /**
   * Creates a new ResponseHeader RecordBuilder.
   * @return A new ResponseHeader RecordBuilder
   */
  public static com.anz.fastpayment.inward.avro.ResponseHeader.Builder newBuilder() {
    return new com.anz.fastpayment.inward.avro.ResponseHeader.Builder();
  }

  /**
   * Creates a new ResponseHeader RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ResponseHeader RecordBuilder
   */
  public static com.anz.fastpayment.inward.avro.ResponseHeader.Builder newBuilder(com.anz.fastpayment.inward.avro.ResponseHeader.Builder other) {
    if (other == null) {
      return new com.anz.fastpayment.inward.avro.ResponseHeader.Builder();
    } else {
      return new com.anz.fastpayment.inward.avro.ResponseHeader.Builder(other);
    }
  }

  /**
   * Creates a new ResponseHeader RecordBuilder by copying an existing ResponseHeader instance.
   * @param other The existing instance to copy.
   * @return A new ResponseHeader RecordBuilder
   */
  public static com.anz.fastpayment.inward.avro.ResponseHeader.Builder newBuilder(com.anz.fastpayment.inward.avro.ResponseHeader other) {
    if (other == null) {
      return new com.anz.fastpayment.inward.avro.ResponseHeader.Builder();
    } else {
      return new com.anz.fastpayment.inward.avro.ResponseHeader.Builder(other);
    }
  }

  /**
   * RecordBuilder for ResponseHeader instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ResponseHeader>
    implements org.apache.avro.data.RecordBuilder<ResponseHeader> {

    /** Unique message identifier */
    private java.lang.String MessageId;
    /** Message creation timestamp */
    private java.lang.String CreationDateTime;
    /** When processing completed */
    private java.lang.String ProcessingDateTime;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.anz.fastpayment.inward.avro.ResponseHeader.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.MessageId)) {
        this.MessageId = data().deepCopy(fields()[0].schema(), other.MessageId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.CreationDateTime)) {
        this.CreationDateTime = data().deepCopy(fields()[1].schema(), other.CreationDateTime);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.ProcessingDateTime)) {
        this.ProcessingDateTime = data().deepCopy(fields()[2].schema(), other.ProcessingDateTime);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing ResponseHeader instance
     * @param other The existing instance to copy.
     */
    private Builder(com.anz.fastpayment.inward.avro.ResponseHeader other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.MessageId)) {
        this.MessageId = data().deepCopy(fields()[0].schema(), other.MessageId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.CreationDateTime)) {
        this.CreationDateTime = data().deepCopy(fields()[1].schema(), other.CreationDateTime);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.ProcessingDateTime)) {
        this.ProcessingDateTime = data().deepCopy(fields()[2].schema(), other.ProcessingDateTime);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'MessageId' field.
      * Unique message identifier
      * @return The value.
      */
    public java.lang.String getMessageId() {
      return MessageId;
    }


    /**
      * Sets the value of the 'MessageId' field.
      * Unique message identifier
      * @param value The value of 'MessageId'.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.ResponseHeader.Builder setMessageId(java.lang.String value) {
      validate(fields()[0], value);
      this.MessageId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'MessageId' field has been set.
      * Unique message identifier
      * @return True if the 'MessageId' field has been set, false otherwise.
      */
    public boolean hasMessageId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'MessageId' field.
      * Unique message identifier
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.ResponseHeader.Builder clearMessageId() {
      MessageId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'CreationDateTime' field.
      * Message creation timestamp
      * @return The value.
      */
    public java.lang.String getCreationDateTime() {
      return CreationDateTime;
    }


    /**
      * Sets the value of the 'CreationDateTime' field.
      * Message creation timestamp
      * @param value The value of 'CreationDateTime'.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.ResponseHeader.Builder setCreationDateTime(java.lang.String value) {
      validate(fields()[1], value);
      this.CreationDateTime = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'CreationDateTime' field has been set.
      * Message creation timestamp
      * @return True if the 'CreationDateTime' field has been set, false otherwise.
      */
    public boolean hasCreationDateTime() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'CreationDateTime' field.
      * Message creation timestamp
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.ResponseHeader.Builder clearCreationDateTime() {
      CreationDateTime = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'ProcessingDateTime' field.
      * When processing completed
      * @return The value.
      */
    public java.lang.String getProcessingDateTime() {
      return ProcessingDateTime;
    }


    /**
      * Sets the value of the 'ProcessingDateTime' field.
      * When processing completed
      * @param value The value of 'ProcessingDateTime'.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.ResponseHeader.Builder setProcessingDateTime(java.lang.String value) {
      validate(fields()[2], value);
      this.ProcessingDateTime = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'ProcessingDateTime' field has been set.
      * When processing completed
      * @return True if the 'ProcessingDateTime' field has been set, false otherwise.
      */
    public boolean hasProcessingDateTime() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'ProcessingDateTime' field.
      * When processing completed
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.ResponseHeader.Builder clearProcessingDateTime() {
      ProcessingDateTime = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ResponseHeader build() {
      try {
        ResponseHeader record = new ResponseHeader();
        record.MessageId = fieldSetFlags()[0] ? this.MessageId : (java.lang.String) defaultValue(fields()[0]);
        record.CreationDateTime = fieldSetFlags()[1] ? this.CreationDateTime : (java.lang.String) defaultValue(fields()[1]);
        record.ProcessingDateTime = fieldSetFlags()[2] ? this.ProcessingDateTime : (java.lang.String) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ResponseHeader>
    WRITER$ = (org.apache.avro.io.DatumWriter<ResponseHeader>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ResponseHeader>
    READER$ = (org.apache.avro.io.DatumReader<ResponseHeader>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.MessageId);

    out.writeString(this.CreationDateTime);

    out.writeString(this.ProcessingDateTime);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.MessageId = in.readString();

      this.CreationDateTime = in.readString();

      this.ProcessingDateTime = in.readString();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.MessageId = in.readString();
          break;

        case 1:
          this.CreationDateTime = in.readString();
          break;

        case 2:
          this.ProcessingDateTime = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










