/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.anz.fastpayment.inward.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ResponseBody extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6886145739839562180L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ResponseBody\",\"namespace\":\"com.anz.fastpayment.inward.avro\",\"fields\":[{\"name\":\"OriginalMessage\",\"type\":\"bytes\",\"doc\":\"Original input message preserved as bytes\"},{\"name\":\"TransactionId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Transaction identifier\"},{\"name\":\"ProcessingStatus\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Overall processing status\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ResponseBody> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ResponseBody> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ResponseBody> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ResponseBody> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ResponseBody> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ResponseBody to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ResponseBody from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ResponseBody instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ResponseBody fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Original input message preserved as bytes */
  private java.nio.ByteBuffer OriginalMessage;
  /** Transaction identifier */
  private java.lang.String TransactionId;
  /** Overall processing status */
  private java.lang.String ProcessingStatus;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ResponseBody() {}

  /**
   * All-args constructor.
   * @param OriginalMessage Original input message preserved as bytes
   * @param TransactionId Transaction identifier
   * @param ProcessingStatus Overall processing status
   */
  public ResponseBody(java.nio.ByteBuffer OriginalMessage, java.lang.String TransactionId, java.lang.String ProcessingStatus) {
    this.OriginalMessage = OriginalMessage;
    this.TransactionId = TransactionId;
    this.ProcessingStatus = ProcessingStatus;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return OriginalMessage;
    case 1: return TransactionId;
    case 2: return ProcessingStatus;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: OriginalMessage = (java.nio.ByteBuffer)value$; break;
    case 1: TransactionId = value$ != null ? value$.toString() : null; break;
    case 2: ProcessingStatus = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'OriginalMessage' field.
   * @return Original input message preserved as bytes
   */
  public java.nio.ByteBuffer getOriginalMessage() {
    return OriginalMessage;
  }


  /**
   * Sets the value of the 'OriginalMessage' field.
   * Original input message preserved as bytes
   * @param value the value to set.
   */
  public void setOriginalMessage(java.nio.ByteBuffer value) {
    this.OriginalMessage = value;
  }

  /**
   * Gets the value of the 'TransactionId' field.
   * @return Transaction identifier
   */
  public java.lang.String getTransactionId() {
    return TransactionId;
  }


  /**
   * Sets the value of the 'TransactionId' field.
   * Transaction identifier
   * @param value the value to set.
   */
  public void setTransactionId(java.lang.String value) {
    this.TransactionId = value;
  }

  /**
   * Gets the value of the 'ProcessingStatus' field.
   * @return Overall processing status
   */
  public java.lang.String getProcessingStatus() {
    return ProcessingStatus;
  }


  /**
   * Sets the value of the 'ProcessingStatus' field.
   * Overall processing status
   * @param value the value to set.
   */
  public void setProcessingStatus(java.lang.String value) {
    this.ProcessingStatus = value;
  }

  /**
   * Creates a new ResponseBody RecordBuilder.
   * @return A new ResponseBody RecordBuilder
   */
  public static com.anz.fastpayment.inward.avro.ResponseBody.Builder newBuilder() {
    return new com.anz.fastpayment.inward.avro.ResponseBody.Builder();
  }

  /**
   * Creates a new ResponseBody RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ResponseBody RecordBuilder
   */
  public static com.anz.fastpayment.inward.avro.ResponseBody.Builder newBuilder(com.anz.fastpayment.inward.avro.ResponseBody.Builder other) {
    if (other == null) {
      return new com.anz.fastpayment.inward.avro.ResponseBody.Builder();
    } else {
      return new com.anz.fastpayment.inward.avro.ResponseBody.Builder(other);
    }
  }

  /**
   * Creates a new ResponseBody RecordBuilder by copying an existing ResponseBody instance.
   * @param other The existing instance to copy.
   * @return A new ResponseBody RecordBuilder
   */
  public static com.anz.fastpayment.inward.avro.ResponseBody.Builder newBuilder(com.anz.fastpayment.inward.avro.ResponseBody other) {
    if (other == null) {
      return new com.anz.fastpayment.inward.avro.ResponseBody.Builder();
    } else {
      return new com.anz.fastpayment.inward.avro.ResponseBody.Builder(other);
    }
  }

  /**
   * RecordBuilder for ResponseBody instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ResponseBody>
    implements org.apache.avro.data.RecordBuilder<ResponseBody> {

    /** Original input message preserved as bytes */
    private java.nio.ByteBuffer OriginalMessage;
    /** Transaction identifier */
    private java.lang.String TransactionId;
    /** Overall processing status */
    private java.lang.String ProcessingStatus;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.anz.fastpayment.inward.avro.ResponseBody.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.OriginalMessage)) {
        this.OriginalMessage = data().deepCopy(fields()[0].schema(), other.OriginalMessage);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.TransactionId)) {
        this.TransactionId = data().deepCopy(fields()[1].schema(), other.TransactionId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.ProcessingStatus)) {
        this.ProcessingStatus = data().deepCopy(fields()[2].schema(), other.ProcessingStatus);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing ResponseBody instance
     * @param other The existing instance to copy.
     */
    private Builder(com.anz.fastpayment.inward.avro.ResponseBody other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.OriginalMessage)) {
        this.OriginalMessage = data().deepCopy(fields()[0].schema(), other.OriginalMessage);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.TransactionId)) {
        this.TransactionId = data().deepCopy(fields()[1].schema(), other.TransactionId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.ProcessingStatus)) {
        this.ProcessingStatus = data().deepCopy(fields()[2].schema(), other.ProcessingStatus);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'OriginalMessage' field.
      * Original input message preserved as bytes
      * @return The value.
      */
    public java.nio.ByteBuffer getOriginalMessage() {
      return OriginalMessage;
    }


    /**
      * Sets the value of the 'OriginalMessage' field.
      * Original input message preserved as bytes
      * @param value The value of 'OriginalMessage'.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.ResponseBody.Builder setOriginalMessage(java.nio.ByteBuffer value) {
      validate(fields()[0], value);
      this.OriginalMessage = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'OriginalMessage' field has been set.
      * Original input message preserved as bytes
      * @return True if the 'OriginalMessage' field has been set, false otherwise.
      */
    public boolean hasOriginalMessage() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'OriginalMessage' field.
      * Original input message preserved as bytes
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.ResponseBody.Builder clearOriginalMessage() {
      OriginalMessage = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'TransactionId' field.
      * Transaction identifier
      * @return The value.
      */
    public java.lang.String getTransactionId() {
      return TransactionId;
    }


    /**
      * Sets the value of the 'TransactionId' field.
      * Transaction identifier
      * @param value The value of 'TransactionId'.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.ResponseBody.Builder setTransactionId(java.lang.String value) {
      validate(fields()[1], value);
      this.TransactionId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'TransactionId' field has been set.
      * Transaction identifier
      * @return True if the 'TransactionId' field has been set, false otherwise.
      */
    public boolean hasTransactionId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'TransactionId' field.
      * Transaction identifier
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.ResponseBody.Builder clearTransactionId() {
      TransactionId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'ProcessingStatus' field.
      * Overall processing status
      * @return The value.
      */
    public java.lang.String getProcessingStatus() {
      return ProcessingStatus;
    }


    /**
      * Sets the value of the 'ProcessingStatus' field.
      * Overall processing status
      * @param value The value of 'ProcessingStatus'.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.ResponseBody.Builder setProcessingStatus(java.lang.String value) {
      validate(fields()[2], value);
      this.ProcessingStatus = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'ProcessingStatus' field has been set.
      * Overall processing status
      * @return True if the 'ProcessingStatus' field has been set, false otherwise.
      */
    public boolean hasProcessingStatus() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'ProcessingStatus' field.
      * Overall processing status
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.ResponseBody.Builder clearProcessingStatus() {
      ProcessingStatus = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ResponseBody build() {
      try {
        ResponseBody record = new ResponseBody();
        record.OriginalMessage = fieldSetFlags()[0] ? this.OriginalMessage : (java.nio.ByteBuffer) defaultValue(fields()[0]);
        record.TransactionId = fieldSetFlags()[1] ? this.TransactionId : (java.lang.String) defaultValue(fields()[1]);
        record.ProcessingStatus = fieldSetFlags()[2] ? this.ProcessingStatus : (java.lang.String) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ResponseBody>
    WRITER$ = (org.apache.avro.io.DatumWriter<ResponseBody>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ResponseBody>
    READER$ = (org.apache.avro.io.DatumReader<ResponseBody>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeBytes(this.OriginalMessage);

    out.writeString(this.TransactionId);

    out.writeString(this.ProcessingStatus);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.OriginalMessage = in.readBytes(this.OriginalMessage);

      this.TransactionId = in.readString();

      this.ProcessingStatus = in.readString();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.OriginalMessage = in.readBytes(this.OriginalMessage);
          break;

        case 1:
          this.TransactionId = in.readString();
          break;

        case 2:
          this.ProcessingStatus = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










