/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.anz.fastpayment.inward.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ToAcct extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1910860165602626629L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ToAcct\",\"namespace\":\"com.anz.fastpayment.inward.avro\",\"fields\":[{\"name\":\"AcctId\",\"type\":\"string\",\"doc\":\"Account identifier\"},{\"name\":\"CurCode\",\"type\":\"string\",\"doc\":\"Currency code\"},{\"name\":\"Amount\",\"type\":\"double\",\"doc\":\"Amount\"},{\"name\":\"Narrative\",\"type\":\"string\",\"doc\":\"Narrative\"},{\"name\":\"AcctUse\",\"type\":\"string\",\"doc\":\"Account use\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ToAcct> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ToAcct> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ToAcct> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ToAcct> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ToAcct> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ToAcct to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ToAcct from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ToAcct instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ToAcct fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Account identifier */
  private java.lang.CharSequence AcctId;
  /** Currency code */
  private java.lang.CharSequence CurCode;
  /** Amount */
  private double Amount;
  /** Narrative */
  private java.lang.CharSequence Narrative;
  /** Account use */
  private java.lang.CharSequence AcctUse;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ToAcct() {}

  /**
   * All-args constructor.
   * @param AcctId Account identifier
   * @param CurCode Currency code
   * @param Amount Amount
   * @param Narrative Narrative
   * @param AcctUse Account use
   */
  public ToAcct(java.lang.CharSequence AcctId, java.lang.CharSequence CurCode, java.lang.Double Amount, java.lang.CharSequence Narrative, java.lang.CharSequence AcctUse) {
    this.AcctId = AcctId;
    this.CurCode = CurCode;
    this.Amount = Amount;
    this.Narrative = Narrative;
    this.AcctUse = AcctUse;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return AcctId;
    case 1: return CurCode;
    case 2: return Amount;
    case 3: return Narrative;
    case 4: return AcctUse;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: AcctId = (java.lang.CharSequence)value$; break;
    case 1: CurCode = (java.lang.CharSequence)value$; break;
    case 2: Amount = (java.lang.Double)value$; break;
    case 3: Narrative = (java.lang.CharSequence)value$; break;
    case 4: AcctUse = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'AcctId' field.
   * @return Account identifier
   */
  public java.lang.CharSequence getAcctId() {
    return AcctId;
  }


  /**
   * Sets the value of the 'AcctId' field.
   * Account identifier
   * @param value the value to set.
   */
  public void setAcctId(java.lang.CharSequence value) {
    this.AcctId = value;
  }

  /**
   * Gets the value of the 'CurCode' field.
   * @return Currency code
   */
  public java.lang.CharSequence getCurCode() {
    return CurCode;
  }


  /**
   * Sets the value of the 'CurCode' field.
   * Currency code
   * @param value the value to set.
   */
  public void setCurCode(java.lang.CharSequence value) {
    this.CurCode = value;
  }

  /**
   * Gets the value of the 'Amount' field.
   * @return Amount
   */
  public double getAmount() {
    return Amount;
  }


  /**
   * Sets the value of the 'Amount' field.
   * Amount
   * @param value the value to set.
   */
  public void setAmount(double value) {
    this.Amount = value;
  }

  /**
   * Gets the value of the 'Narrative' field.
   * @return Narrative
   */
  public java.lang.CharSequence getNarrative() {
    return Narrative;
  }


  /**
   * Sets the value of the 'Narrative' field.
   * Narrative
   * @param value the value to set.
   */
  public void setNarrative(java.lang.CharSequence value) {
    this.Narrative = value;
  }

  /**
   * Gets the value of the 'AcctUse' field.
   * @return Account use
   */
  public java.lang.CharSequence getAcctUse() {
    return AcctUse;
  }


  /**
   * Sets the value of the 'AcctUse' field.
   * Account use
   * @param value the value to set.
   */
  public void setAcctUse(java.lang.CharSequence value) {
    this.AcctUse = value;
  }

  /**
   * Creates a new ToAcct RecordBuilder.
   * @return A new ToAcct RecordBuilder
   */
  public static com.anz.fastpayment.inward.avro.ToAcct.Builder newBuilder() {
    return new com.anz.fastpayment.inward.avro.ToAcct.Builder();
  }

  /**
   * Creates a new ToAcct RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ToAcct RecordBuilder
   */
  public static com.anz.fastpayment.inward.avro.ToAcct.Builder newBuilder(com.anz.fastpayment.inward.avro.ToAcct.Builder other) {
    if (other == null) {
      return new com.anz.fastpayment.inward.avro.ToAcct.Builder();
    } else {
      return new com.anz.fastpayment.inward.avro.ToAcct.Builder(other);
    }
  }

  /**
   * Creates a new ToAcct RecordBuilder by copying an existing ToAcct instance.
   * @param other The existing instance to copy.
   * @return A new ToAcct RecordBuilder
   */
  public static com.anz.fastpayment.inward.avro.ToAcct.Builder newBuilder(com.anz.fastpayment.inward.avro.ToAcct other) {
    if (other == null) {
      return new com.anz.fastpayment.inward.avro.ToAcct.Builder();
    } else {
      return new com.anz.fastpayment.inward.avro.ToAcct.Builder(other);
    }
  }

  /**
   * RecordBuilder for ToAcct instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ToAcct>
    implements org.apache.avro.data.RecordBuilder<ToAcct> {

    /** Account identifier */
    private java.lang.CharSequence AcctId;
    /** Currency code */
    private java.lang.CharSequence CurCode;
    /** Amount */
    private double Amount;
    /** Narrative */
    private java.lang.CharSequence Narrative;
    /** Account use */
    private java.lang.CharSequence AcctUse;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.anz.fastpayment.inward.avro.ToAcct.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.AcctId)) {
        this.AcctId = data().deepCopy(fields()[0].schema(), other.AcctId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.CurCode)) {
        this.CurCode = data().deepCopy(fields()[1].schema(), other.CurCode);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.Amount)) {
        this.Amount = data().deepCopy(fields()[2].schema(), other.Amount);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.Narrative)) {
        this.Narrative = data().deepCopy(fields()[3].schema(), other.Narrative);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.AcctUse)) {
        this.AcctUse = data().deepCopy(fields()[4].schema(), other.AcctUse);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing ToAcct instance
     * @param other The existing instance to copy.
     */
    private Builder(com.anz.fastpayment.inward.avro.ToAcct other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.AcctId)) {
        this.AcctId = data().deepCopy(fields()[0].schema(), other.AcctId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.CurCode)) {
        this.CurCode = data().deepCopy(fields()[1].schema(), other.CurCode);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.Amount)) {
        this.Amount = data().deepCopy(fields()[2].schema(), other.Amount);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.Narrative)) {
        this.Narrative = data().deepCopy(fields()[3].schema(), other.Narrative);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.AcctUse)) {
        this.AcctUse = data().deepCopy(fields()[4].schema(), other.AcctUse);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'AcctId' field.
      * Account identifier
      * @return The value.
      */
    public java.lang.CharSequence getAcctId() {
      return AcctId;
    }


    /**
      * Sets the value of the 'AcctId' field.
      * Account identifier
      * @param value The value of 'AcctId'.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.ToAcct.Builder setAcctId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.AcctId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'AcctId' field has been set.
      * Account identifier
      * @return True if the 'AcctId' field has been set, false otherwise.
      */
    public boolean hasAcctId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'AcctId' field.
      * Account identifier
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.ToAcct.Builder clearAcctId() {
      AcctId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'CurCode' field.
      * Currency code
      * @return The value.
      */
    public java.lang.CharSequence getCurCode() {
      return CurCode;
    }


    /**
      * Sets the value of the 'CurCode' field.
      * Currency code
      * @param value The value of 'CurCode'.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.ToAcct.Builder setCurCode(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.CurCode = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'CurCode' field has been set.
      * Currency code
      * @return True if the 'CurCode' field has been set, false otherwise.
      */
    public boolean hasCurCode() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'CurCode' field.
      * Currency code
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.ToAcct.Builder clearCurCode() {
      CurCode = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'Amount' field.
      * Amount
      * @return The value.
      */
    public double getAmount() {
      return Amount;
    }


    /**
      * Sets the value of the 'Amount' field.
      * Amount
      * @param value The value of 'Amount'.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.ToAcct.Builder setAmount(double value) {
      validate(fields()[2], value);
      this.Amount = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'Amount' field has been set.
      * Amount
      * @return True if the 'Amount' field has been set, false otherwise.
      */
    public boolean hasAmount() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'Amount' field.
      * Amount
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.ToAcct.Builder clearAmount() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'Narrative' field.
      * Narrative
      * @return The value.
      */
    public java.lang.CharSequence getNarrative() {
      return Narrative;
    }


    /**
      * Sets the value of the 'Narrative' field.
      * Narrative
      * @param value The value of 'Narrative'.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.ToAcct.Builder setNarrative(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.Narrative = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'Narrative' field has been set.
      * Narrative
      * @return True if the 'Narrative' field has been set, false otherwise.
      */
    public boolean hasNarrative() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'Narrative' field.
      * Narrative
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.ToAcct.Builder clearNarrative() {
      Narrative = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'AcctUse' field.
      * Account use
      * @return The value.
      */
    public java.lang.CharSequence getAcctUse() {
      return AcctUse;
    }


    /**
      * Sets the value of the 'AcctUse' field.
      * Account use
      * @param value The value of 'AcctUse'.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.ToAcct.Builder setAcctUse(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.AcctUse = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'AcctUse' field has been set.
      * Account use
      * @return True if the 'AcctUse' field has been set, false otherwise.
      */
    public boolean hasAcctUse() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'AcctUse' field.
      * Account use
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.ToAcct.Builder clearAcctUse() {
      AcctUse = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ToAcct build() {
      try {
        ToAcct record = new ToAcct();
        record.AcctId = fieldSetFlags()[0] ? this.AcctId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.CurCode = fieldSetFlags()[1] ? this.CurCode : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.Amount = fieldSetFlags()[2] ? this.Amount : (java.lang.Double) defaultValue(fields()[2]);
        record.Narrative = fieldSetFlags()[3] ? this.Narrative : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.AcctUse = fieldSetFlags()[4] ? this.AcctUse : (java.lang.CharSequence) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ToAcct>
    WRITER$ = (org.apache.avro.io.DatumWriter<ToAcct>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ToAcct>
    READER$ = (org.apache.avro.io.DatumReader<ToAcct>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.AcctId);

    out.writeString(this.CurCode);

    out.writeDouble(this.Amount);

    out.writeString(this.Narrative);

    out.writeString(this.AcctUse);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.AcctId = in.readString(this.AcctId instanceof Utf8 ? (Utf8)this.AcctId : null);

      this.CurCode = in.readString(this.CurCode instanceof Utf8 ? (Utf8)this.CurCode : null);

      this.Amount = in.readDouble();

      this.Narrative = in.readString(this.Narrative instanceof Utf8 ? (Utf8)this.Narrative : null);

      this.AcctUse = in.readString(this.AcctUse instanceof Utf8 ? (Utf8)this.AcctUse : null);

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.AcctId = in.readString(this.AcctId instanceof Utf8 ? (Utf8)this.AcctId : null);
          break;

        case 1:
          this.CurCode = in.readString(this.CurCode instanceof Utf8 ? (Utf8)this.CurCode : null);
          break;

        case 2:
          this.Amount = in.readDouble();
          break;

        case 3:
          this.Narrative = in.readString(this.Narrative instanceof Utf8 ? (Utf8)this.Narrative : null);
          break;

        case 4:
          this.AcctUse = in.readString(this.AcctUse instanceof Utf8 ? (Utf8)this.AcctUse : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










